### ISSUE TITLE
error: unknown option `---END'

### ISSUE THREAD

**Issue by leungyukshing** [JamesIves/github-pages-deploy-action#100]
**Describe the bug**

> Please provide a clear and concise description of what the bug is.
https://github.com/Kok-Kip/frontend/blob/master/.github/workflows/nodejs.yml
this is my workflow and I failed to push my docs/ folder to my gh-pages branches for github pages deployment
**Reproduce**

> Steps to reproduce the behavior.

**Expected behavior**

> Please provide a clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Additional Comments**

> Add any other context about the problem here.

**Comment by JamesIves** [comment]
I don't see where in your workflow yml file that you're using this action?
