### ISSUE TITLE
Deployments for commits landed in quick succession may fail because of TOCTOU issue

### ISSUE THREAD

**Issue by sunshowers** [JamesIves/github-pages-deploy-action#1000]
Thank you for writing this action! It generally works quite well, though I've noticed one bug in it so far:

## Describe the bug

If two or more commits are landed in quick succession, deployments may fail, or earlier deployments may override later ones, because of a [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) issue.

## Reproduction Steps

Consider these scenarios:
**Scenario A**: 
1. Commits aa and bb (in this order) are landed in quick succession
2. Deployment workflows kick off for aa and bb at roughly the same time.
3. Building pages for bb completes *immediately after* the one for aa.
4. Deploying bb fails because of "cannot lock ref".

**Scenario B**:
1. Commits aa and bb (in this order) are landed in quick succession
2. Deployment workflows kick off for aa and bb at roughly the same time.
3. Building pages and deployment for bb completes *before* the one for aa.
4. The deployment for aa, because of `git push --force` [here](https://github.com/JamesIves/github-pages-deploy-action/blob/a7cf017c75575c49ff7bea51176f2336ba8d331c/src/git.ts#L220-L223), overwrites the one for bb even though aa is an outdated version.

**Scenario C**:
1. Commit aa is landed, and then bb is landed in quick succession as a force push that edits aa.
2. Deployment workflows kick off for aa and bb at roughly the same time.
3. Building pages and deployment for bb completes *before* the one for aa.
4. The deployment for aa, because of `git push --force` [here](https://github.com/JamesIves/github-pages-deploy-action/blob/a7cf017c75575c49ff7bea51176f2336ba8d331c/src/git.ts#L220-L223), overwrites the one for bb even though aa is an outdated version.

## Logs

Here's an example of **scenario A**:

```sh
/usr/bin/git checkout -b github-pages-deploy-action/jlfxau6uv
Switched to a new branch 'github-pages-deploy-action/jlfxau6uv'
/usr/bin/git commit -m Deploying to gh-pages from  @ 2677d4e0e9811901c9d532be2b30f6bc500f4040 🚀 --quiet --no-verify
/usr/bin/git push --force ***github.com/facebookincubator/cargo-guppy.git github-pages-deploy-action/jlfxau6uv:gh-pages
To facebookincubator/cargo-guppy.git
 ! [remote rejected]       github-pages-deploy-action/jlfxau6uv -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at 77d3ed39a4854a5c93072a97a43566aef7bacabd but expected a7cedf9d6f450f0feea7a44e8764dfeb032e2d60)
error: failed to push some refs to 'facebookincubator/cargo-guppy.git'
```

**Scenarios B and C** are a bit harder to detect because they are marked as successes, but they can definitely happen based on my examination of the codebase.

## Workflow

[Link to a docs.yml file.](https://github.com/facebookincubator/cargo-guppy/blob/b3addea52e7ac8052a8bb8d95e8e99be63f4e005/.github/workflows/docs.yml)

## Recommended solution

git does not provide a way to lock a repository for a particular duration, so the solution requires [optimistic concurrency](https://en.wikipedia.org/wiki/Optimistic_concurrency_control).

I believe that the correct way to do this would be:
1. Remove `--force` from the git push: let it fail for non-fast-forward pushes. This will cause the job to fail for scenarios B and C.
2. In case of a failure in `git push`, fetch the latest version of the main branch (or whatever source branch there is) and the gh-pages branch.
3. Grab the latest commit message from the gh-pages branch:
   ```sh
   git log refs/remotes/origin/gh-pages --max-count 1 --format=tformat:%s --
   ```
4. The commit message looks something like `Deploying to gh-pages from  @ 85aa7a47ce50001840d3e87a01253dfb17c6e85e 🚀`.  Parse this to grab `85aa7a47ce50001840d3e87a01253dfb17c6e85e` from the message (hereafter shortened to `85aa7a4`). This should refer to a commit in the source branch. (If it doesn't, probably best to fail).
5. This will lead to (time flows to the right):
  a. **Scenario A:**
      ```sh
              85aa7a4    current
       o---------o---------o
      ```
    b. **Scenario B:**
      ```sh
             current    85aa7a4
      o---------o---------o
      ```

    c. **Scenario C:**
      ```sh
        ---o current
       /
      o
       \
        ---o 85aa7a4
      ```
6. To handle these scenarios, run: ```git merge-base <current> 85aa7a4```. This can produce one of three answers:
  a. `85aa7a4`: this is **scenario A**. In this case, simply retry the push.
  b. `current`: this is **scenario B**. In this case, exit the job and assume that the build job for `85aa7a4` included `current`. (This assumption may not always be valid, so maybe provide a config option that causes an error in this case.)
  c. Something else: this is **scenario C**. The easy fix would be to just error out here since in general people should not be force-pushing to their main branches, but it can probably be handled using committer times and the `--force-with-lease` option to `git push`. (Basically, if the committer time is newer assume that it's newer.)
  
A retry limit of 5 or so is reasonable, and it could be made configurable I guess.

**Comment by JamesIves** [comment]
Thanks for the report and the research you've put into it. The nature of git makes this a pretty tricky thing to reliably solve without introducing a number of bugs as a result. In step 4 you mentioned referencing the commit message, which unfortunately won't work you're allowed to modify this message entirely using the `commit-message` field. 

As this feels like a pretty rare bug you'd encounter only if you're making deployment commits in very quick succession I'm leaning towards marking this as won't fix, and instead leveraging the [concurrency field](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) in the workflow examples provided in the docs. For example:

```yml
name: Deploy
on:
  push:	
    branches:	
      - dev
jobs:  
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.18.1'

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: |
          npm ci
          npm run-script build

      - name: Build and Deploy Repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: 'public'
```

Using this option will make your workflow runs queue up. If there's more than 2 in the queue the first one will complete, followed by the last one, and GitHub will cancel any in-between. It seems like in most cases this is only occurring from deployments happening from Dependabot or something similar, and if the aim is a deployment you're likely only wanting to validate the final job anyway as that will contain all of the changes that were rapidly committed. For workflows that use the matrix options there's a max-parallel property which can be leveraged to do something similar too.

Here's an example of the workflow I posted above with a series of commits I fired off one after another. Note the middle one is cancelled, and the final one is queued. It will remain queued until the first one is finished, causing the last job to contain everything from the previous two. 

<img width="951" alt="Screen Shot 2022-01-11 at 8 34 50 AM" src="https://user-images.githubusercontent.com/10888441/148952520-da134ff0-780c-4394-b857-002f688aea13.png">

I'm cautious to completely change how we're pulling commits as this could become quite error prone especially as seems like something that can be resolved through the tools provided by GitHub already.

**Comment by sunshowers** [comment]
That's excellent! I didn't actually know that option existed, and I've spent quite a lot of time with GitHub actions. Would you consider recommending this in the README? Seems like this may bite others too.

**Comment by JamesIves** [comment]
For sure! I should be able to add that tomorrow morning. I'll leave this open until I've made the change.

**Comment by JamesIves** [comment]
This has been added to the README under the Getting Started section!
