### ISSUE TITLE
Permissions error - send_files failed to open file: Permission denied.

### ISSUE THREAD

**Issue by jedahan** [JamesIves/github-pages-deploy-action#1034]
Checked the QA forums, and https://github.com/JamesIves/github-pages-deploy-action/discussions/1011 looks similar but not exactly the same bug.

## Describe the bug

Permissions error with rsync: ` rsync: send_files failed to open "/home/runner/work/kiss-find/kiss-find/build/web/index.html": Permission denied (13)`

## Reproduction Steps

Fork and run the 'build' action from repo https://github.com/jedahan/kiss-find .

## Logs
I set `ACTIONS_STEP_DEBUG` to `true` in the Actions secrets menu.

https://github.com/jedahan/kiss-find/runs/5190619827?check_suite_focus=true

## Workflow

Workflow file: https://github.com/jedahan/kiss-find/blob/main/.github/workflows/build.yaml

**Comment by JamesIves** [comment]
This is a permission based error likely due to how your deployment folder is being generated. Are you able to relax the permissions on these directories so rsync can perform its steps? I did a quick Google on the issue and [this might help](https://unix.stackexchange.com/questions/578805/rsync-failed-permission-denied-13-ubuntu).

**Comment by JamesIves** [comment]
If you have a spare moment, do you mind trying `JamesIves/github-pages-deploy-action@releases/v4-permission`? I'm testing a variation of this which writes `777` to the folder that is set to be deployed which may fix this problem for you.

**Comment by jedahan** [comment]
Thank you! Will let you know if the next run succeeds in a few hours.

**Comment by jedahan** [comment]
That fixed it for me, thank you!

**Comment by jedahan** [comment]
Though its a bit concerning that now all my github pages files are 'executable' even though they are just html and css.

Maybe 777 is a bit aggressive and it should be something like 644? Or simply `chown -R $USER`?

**Comment by jedahan** [comment]
Example output is https://github.com/jedahan/kiss-find/tree/github-pages

**Comment by JamesIves** [comment]
Yeah I just wanted to validate that this was something that could be solved with permissions hence the aggressive approach. I will open a pull request for this tomorrow morning and cut a new release with proper changes/implementation.

**Comment by JamesIves** [comment]
If you don't mind can you try it one more? I've modified the permission to `+rw`, I'm hoping that is sufficient enough.

**Comment by jedahan** [comment]
I wonder if it needs to be recursive, or if maybe my build step output has wrong permissions for some reason. See https://github.com/jedahan/kiss-find/runs/5447831745?check_suite_focus=true for failing log

**Comment by jedahan** [comment]
Maybe it also needs to be `chmod -R +rw` for some reason?

**Comment by JamesIves** [comment]
The test version should be updated with that modification now

**Comment by JamesIves** [comment]
^ Lemme know if this looks good to you

**Comment by jedahan** [comment]
Yep, has been working well, thank you!
