### ISSUE TITLE
First deployment to non-existent branch fails

### ISSUE THREAD

**Issue by brockfanning** [JamesIves/github-pages-deploy-action#107]
**Describe the bug**

The first time a deployment is triggered, on a repository that has no gh-pages branch, the deployment fails. The error message is "fatal: invalid reference: origin/gh-pages". (The next time a deployment is triggered, it works fine.)

**Reproduce**

[Here](https://github.com/brockfanning/deleteme/commit/0a7cd46c3ac7ff8007fa1f59cfaa3788079bad28/checks?check_suite_id=387267890#step:6:55) is an example of the failure. [Here](https://github.com/brockfanning/deleteme/blob/develop/.github/workflows/deploy-to-staging.yml) is the workflow config.

**Expected behavior**

The deployment should succeed even if the branch doesn't exist.

**Additional Comments**

I thought it might be related to #74 but I am already using actions/checkout@v1.

**Comment by JamesIves** [comment]
Thanks for the report. Here's the PR for this fix: https://github.com/JamesIves/github-pages-deploy-action/pull/108

Let me know if that works and I'll push up the release tomorrow.

**Comment by JamesIves** [comment]
This has been fixed in version `3.1.2` which is going up now.
