### ISSUE TITLE
when publish， causing timeout error

### ISSUE THREAD

**Issue by xingangshi** [JamesIves/github-pages-deploy-action#1088]
```

Digest: sha256:5315d7583ad7e2e9f11655150f7cf7de956099fa15a9b0d598f9fa6d39b23f41
Status: Downloaded newer image for ghcr.io/pengx17/logseq-publish:master
Page loaded!
Graph loaded for /home/logseq/graph
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".button >> i.ti-dots"
============================================================
    at publish (file:///home/logseq/publish.mjs:119:14)
    at async main (file:///home/logseq/publish.mjs:202:5) {
  name: 'TimeoutError'
}
Trace file saved to /home/logseq/graph/www/trace.zip
Export failed
Run actions/upload-artifact@v2
  with:
    name: trace
    path: www/trace.zip
  
    if-no-files-found: warn
With the provided path, there will be 1 file uploaded
Starting artifact upload

```

**Comment by JamesIves** [comment]
This doesn't look to be related to this project. Please fill out the issue template and resubmit.

**Comment by xingangshi** [comment]
> This doesn't look to be related to this project. Please fill out the issue template and resubmit.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@v0.1
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: copy assets
        run: sudo bash org_cp_assets.sh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.2

        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          single-commit: true
Code Intelligence Preview
