### ISSUE TITLE
Wrong Request URL

### ISSUE THREAD

**Issue by subaquatic-pierre** [JamesIves/github-pages-deploy-action#1114]
I have used this workflow to create a React App build and publish to GitHub pages.

It is not requesting the correct URL for main.9867edbc.js

It is requesting my root GitHub account

`https://subaquatic-pierre.github.io/static/js/main.9867edbc.js`

and not the actual repo url eg.

`https://subaquatic-pierre.github.io/react-mui-notify-demo/static/js/main.9867edbc.js`

I have tried updating the package.json to include home directory like I have seen in some discussions. 

` "homePage": "https://subaquatic-pierre.github.io/react-mui-notify-demo",`

It is just not referring to the correct domain. It is a nightmare

I have just created a S3 bucket to host the static site for now. Just wanted to check if anyone else has had an issue like this building a React App.

This is the demo repo in which the workflow is.

https://github.com/subaquatic-pierre/react-mui-notify-demo

This is the pages URL where the app is supposed to be deployed.

https://subaquatic-pierre.github.io/react-mui-notify-demo/

This is the S3 bucket with the same build files, it doesnt seem like a build issue. It has something to do with GitHub pages routing.

http://react-mui-demo.s3-website.us-east-2.amazonaws.com/

If anyone has any info would be great :)

**Comment by JamesIves** [comment]
Sorry, this isn't an issue with this action. This is due to a misconfiguration within your create react app.
