### ISSUE TITLE
Aborting commit due to empty commit message

### ISSUE THREAD

**Issue by jia0213** [JamesIves/github-pages-deploy-action#1208]
## Describe the bug

When I used Git Gui to commit , I use the sign off function to generate my commit messages, there is a space line.
So that there occured a problem. I do have the commit messages. Please see the tips in below logs.

## Logs

/usr/bin/git commit -m Signed-off-by: jia0213 <984419317@qq.com> Updated By Github Actions --quiet --no-verify
Aborting commit due to empty commit message.

## Workflow

        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{secrets.IO_SSH}}
          repository-name: jia0213/jia0213.github.io
          branch: main
          folder: public
          commit-message: '${{ github.event.head_commit.message }} Updated By Github Actions'

**Comment by JamesIves** [comment]
Couple of questions- 

* What happens if you remove `${{ github.event.head_commit.message }}`
* What is `${{ github.event.head_commit.message }}`? Wondering if we need to escape any user provided commit message.

**Comment by jia0213** [comment]
It's seemed no important for my action, so I decide to delete It.&nbsp;&nbsp;
I'm very thankful for your answer!Good luck！

&nbsp;


涼ˉ洳閖·』
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "James ***@***.***&gt;; 
发送时间: 2022年9月4日(星期天) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JamesIves/github-pages-deploy-action] Aborting commit due to empty commit message (Issue #1208)






几个问题

如果删除了${{ github.event.head_commit.message }}

什么是${{ github.event.head_commit.message }}? 想知道我们是否需要转义任何用户提供的提交消息。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
