### ISSUE TITLE
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 129 ❌

### ISSUE THREAD

**Issue by StormWangxhu** [JamesIves/github-pages-deploy-action#1229]
## Describe the bug

Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 129 ❌

## Reproduction Steps

https://github.com/StormWangxhu/shenshenmuzi/actions/runs/3155384147/jobs/5133982090

## Workflow

[docs.yml](https://github.com/StormWangxhu/shenshenmuzi/actions/runs/3155384147/jobs/5133982090)

## Additional Comments

please help me,thanks !

I just found 'failed with exit code 128'.

**Comment by maietta** [comment]
You should avoid posting personal information.

**Comment by StormWangxhu** [comment]
> You should avoid posting personal information.

Thanks, I will resubmit the problem description

**Comment by StormWangxhu** [comment]
> You should avoid posting personal information.

How should I go about solving this problem： 'The process '/usr/bin/git' failed with exit code 129'，thanks!

**Comment by saraswatmks** [comment]
I also have the same issue 'The process '/usr/bin/git' failed with exit code 129'

**Comment by yarnetsky** [comment]
similar issue, though mine exited on line 128.

```
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/name-of-repo/name-of-repo
/usr/bin/git config user.name xxxxxxx
fatal: not in a git directory
Error: There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

**Comment by JamesIves** [comment]
Please provide your deployment logs, this is a generic error, and usually, the real reason is listed right before this.

**Comment by yarnetsky** [comment]
Thank you for replying! Happily, I discovered the solution in an answer you gave to another issue. That's also when I realized about "generic errors" and deleted my comment as mine was unrelated to this issue. I'm still learning. Thanks again!

**Comment by dhwaj1902** [comment]
Having the same problem, was using self hosted runners.

**Comment by Jebay** [comment]
Resolved [here](https://github.com/JamesIves/github-pages-deploy-action/issues/1285)

**Comment by luisfontes19** [comment]
By default on new repos the workflows only have read access

You need to explicitly grant write access to the workflow so that it can push to the repo

Add this to your workflow and it should solve the problem:

```yaml
permissions:
  contents: write
```

**Comment by JamesIves** [comment]
Closing as a duplicate.
