### ISSUE TITLE
Warnings from GitHub about Node 12 and set-output being deprecated

### ISSUE THREAD

**Issue by jwodder** [JamesIves/github-pages-deploy-action#1241]
## Describe the bug

When running the latest version of this action (`@v4`), GitHub emits the following warnings as annotations:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: JamesIves/github-pages-deploy-action

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Workflow

https://github.com/jwodder/kbits/blob/master/.github/workflows/deploy.yml

**Comment by JamesIves** [comment]
This has been updated as of version v4.4.1, please let me know if you continue to see this: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/v4.4.1

**Comment by M3lkior** [comment]
hi @JamesIves  ; what about the deprecation of `set-output` ? i don't see the fix in the v4.4.1

**Comment by kelvinqian00** [comment]
@M3lkior I performed a test deployment using v4.4.1 and there was no `set-output` warning. (By contrast, our most recent production deployment was with version 4.1.5 which _did_ have that warning.) So I think we should be good on that regard.

**Comment by M3lkior** [comment]
ok thanks
