### ISSUE TITLE
Error: Ensure GITHUB_TOKEN has permission "idToken: write".

### ISSUE THREAD

**Issue by mathiasbynens** [JamesIves/github-pages-deploy-action#1253]
A workflow that was working fine for weeks suddenly [stopped working](https://github.com/mathiasbynens/tibia-bosses/actions/runs/3294515721/jobs/5432115686#step:2:1) with the following error message:

```
Run actions/deploy-pages@v1
Error: Error message: Cannot read properties of undefined (reading 'message')
    at Function.<anonymous> (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:71:1)
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/actions/deploy-pages/v1/webpack:/deploy-pages/node_modules/@actions/core/lib/oidc-utils.js:6:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Ensure GITHUB_TOKEN has permission "idToken: write".
```

Any ideas as to what might have happened?

The relevant workflow is here: https://github.com/mathiasbynens/tibia-bosses/blob/5a2f78b8a9a325ca0f5f1d709421b2239532826e/.github/workflows/build.yml#L30-L38

I understand the error message points to `actions/deploy-pages` but I don't think I'm using that directly or explicitly, so am posting here in case it's relevant to actions/github-pages-deploy-action. Feel free to close this issue if I got that wrong :)

**Comment by mathiasbynens** [comment]
GitHub responded and acknowledges it's a problem on their end: https://github.com/actions/deploy-pages/issues/71#issuecomment-1287269934

**Comment by Manoj-nathwani** [comment]
This did the trick for me - https://stackoverflow.com/a/76883315/2068836
