### ISSUE TITLE
Links that address to section headers in Markdown files are broken

### ISSUE THREAD

**Issue by olbapbetan** [JamesIves/github-pages-deploy-action#1298]
## Describe the bug
Regarding the README file (and Markdown files in general), section headers do not have a link associated with them unlike what happens in a usual Markdown file in GitHub, this causes links that address to these sections to result broken in the GitHub page generated.

## Reproduction Steps

Suppose you have a Markdown file with at least one section on it and also suppose you have a link addressing to this e.g.
```
go to [the example](#title-of-example)

#title of example
text of example
```
In the generated GitHub page, the link will be broken even though it works correctly if it is being displayed on GitHub as a Markdown file.

**Comment by JamesIves** [comment]
> In the generated GitHub page

This action doesn't generate pages so I'm not sure I'm following the problem here. Can you provide workflow examples?
