### ISSUE TITLE
remote: Permission  denied  when  publish to anonter repository

### ISSUE THREAD

**Issue by lkzwc** [JamesIves/github-pages-deploy-action#1312]
## Describe the bug

i want to build the ffd repository code and to publish lkzwc.github.io repository

this some steps:
1. create keys "Deploy"
![image](https://user-images.githubusercontent.com/84896877/215941730-c2f33ab7-fdfa-4b92-bc6c-a5a24672f650.png)
2. add key "Deploy" to ffd and lkzwc.github.io repository
3. change the two repository workflow permissions write and read

## Logs

this is result : https://github.com/lkzwc/fe-ddu/actions/runs/4060485280/jobs/6990111902

## Workflow

https://github.com/lkzwc/fe-ddu/blob/main/.github/workflows/node.js.yml

**Comment by yizhen23** [comment]
I encountered the same situation as you

**Comment by provinzkraut** [comment]
Encountering the same but only intermittently, which strikes me as odd.

**Comment by JamesIves** [comment]
Did you just provide workflow access? It needs repo write/read too.

**Comment by jinzishuai** [comment]
I had the same problem and I made sure the workflow has write permission

<img width="798" alt="image" src="https://github.com/JamesIves/github-pages-deploy-action/assets/1074685/8df7fbf6-152e-44be-be02-4bdbf4baf20d">

But I wonder if there is more for cross repo workflows.

**Comment by shiwanjun1995** [comment]
> I had the same problem and I made sure the workflow has write permission我遇到了同样的问题，我确保工作流具有写入权限
> 
> <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/1074685/268479529-8df7fbf6-152e-44be-be02-4bdbf4baf20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODUwMDUsIm5iZiI6MTcxMTg4NDcwNSwicGF0aCI6Ii8xMDc0Njg1LzI2ODQ3OTUyOS04ZGY3ZmJmNi0xNTJlLTQ0YmUtYmUwMi00YmRiZjRiYWYyMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMTEzMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZlNWZhY2MxNGQwZjMxYzgwY2U2Y2QwZjY0OWJlNjZhNjQ4NDJjOWU4ZjJmZjJmYjMwNThhYzlmYTdlY2RlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vKMCwVB-3FcVdyuilM3mfZA_Vo1cBKlPf8f2ZJxN_a8">
> But I wonder if there is more for cross repo workflows.但我想知道是否还有更多用于跨存储库工作流的内容。

Do this do not work.
You should check this.

<img width="1169" alt="截屏2024-03-31 下午7 49 41" src="https://github.com/JamesIves/github-pages-deploy-action/assets/38515714/75ecc9ea-34a5-4d0d-98b7-b76fe04cd9da">
