### ISSUE TITLE
Commit fails with "process '/usr/bin/git' failed with exit code 128"

### ISSUE THREAD

**Issue by cmatKhan** [JamesIves/github-pages-deploy-action#1318]
## Describe the bug

The pkgdown gh-pages deploy script fails b/c it can't find `git`

```
Run JamesIves/github-pages-deploy-action@v4.4.1
  
....

/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

This seems to be the same issue as the one closed in #308.

## Reproduction Steps

the script is here:

https://github.com/cmatKhan/brentlabXGBoost/blob/main/.github/workflows/pkgdown.yaml

note that this is modified to use `renv` to handle the dependencies.

**Comment by cmatKhan** [comment]
Nevermind -- my bad. The default is to restrict read/write by actions. 

To fix:

Settings --> Actions --> general --> Workflow permissions

and set to read and write

**Comment by zzworker** [comment]
![image](https://github.com/NathanSkene/EWCE/assets/4323686/27992c7f-40b8-4b0d-bcb7-fad6bd0da131)


> Nevermind -- my bad. The default is to restrict read/write by actions.↳
> 
> To fix:
> 
> Settings --> Actions --> general --> Workflow permissions↳
> 
> and set to read and write↳

not work 
![image](https://github.com/JamesIves/github-pages-deploy-action/assets/4323686/8d7469ec-32af-4231-af78-e8a2107fe724)

name: CI
on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时触发
  push:
    branches: [main] #要生成的logseq库分支名称
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TZ: 'Asia/Shanghai'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3
      - name: Logseq Publish 🚩
        uses: logseq/publish-spa@v0.2.0 #生成html文件，并push到gh-pages分支
        with:
          theme-mode: dark
      - name: add a nojekyll file #标记为非jekyll
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: funv5/logseq_publish  # 公开的仓库地址
          branch: main # The branch the action should deploy to.
          folder: www # The folder the action should deploy. 临时目录名称
          clean: true #始终覆盖更新
          single-commit: true
          trace: false
          token: ${{ secrets.ACCESS_TOKEN }}

**Comment by shiwanjun1995** [comment]
> ![image](https://private-user-images.githubusercontent.com/4323686/299201023-27992c7f-40b8-4b0d-bcb7-fad6bd0da131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzUyNjUsIm5iZiI6MTcxMTg3NDk2NSwicGF0aCI6Ii80MzIzNjg2LzI5OTIwMTAyMy0yNzk5MmM3Zi00MGI4LTRiMGQtYmNiNy1mYWQ2YmQwZGExMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMDg0OTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE4ZjY4MDE5NTgxYjFkM2JjM2VkZDZmMjQyNWYxZWNhYjEyMjFlNDdmYjUwNmRhYmI4OGE4MmYyMjc3OTE5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K82De1-is9HlfGjE94wHFATEkszeIyMmetlgAXrIGi0)
> 
> > Nevermind -- my bad. The default is to restrict read/write by actions.↳
> > To fix:
> > Settings --> Actions --> general --> Workflow permissions↳
> > and set to read and write↳
> 
> not work ![image](https://private-user-images.githubusercontent.com/4323686/299202670-8d7469ec-32af-4231-af78-e8a2107fe724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzUyNjUsIm5iZiI6MTcxMTg3NDk2NSwicGF0aCI6Ii80MzIzNjg2LzI5OTIwMjY3MC04ZDc0NjllYy0zMmFmLTQyMzEtYWY3OC1lOGEyMTA3ZmU3MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMDg0OTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjY0YzE2ZWMyOTg5NWE2M2Y1MTc2NTk0OTU4ZWM2ZDc3ZTlkNWI5ZmM3MmQwNzVhYjMwMzNiNTVmNjMzZTUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DmX5vtlX4vmtBOZiM8wdWtF9kApq49Mqs0yZdF7baTA)
> 
> name: CI on: schedule: - cron: '0 */6 * * *' # 每 6 小时触发 push: branches: [main] #要生成的logseq库分支名称
> 
> # Allows you to run this workflow manually from the Actions tab
> workflow_dispatch:
> 
> env: TZ: 'Asia/Shanghai'
> 
> permissions: contents: write
> 
> jobs: build: runs-on: ubuntu-latest name: Publish Logseq graph steps: - uses: actions/checkout@v3 - name: Logseq Publish 🚩 uses: logseq/publish-spa@v0.2.0 #生成html文件，并push到gh-pages分支 with: theme-mode: dark - name: add a nojekyll file #标记为非jekyll run: touch $GITHUB_WORKSPACE/www/.nojekyll - name: Deploy 🚀 uses: JamesIves/github-pages-deploy-action@v4 with: repository-name: funv5/logseq_publish # 公开的仓库地址 branch: main # The branch the action should deploy to. folder: www # The folder the action should deploy. 临时目录名称 clean: true #始终覆盖更新 single-commit: true trace: false token: ${{ secrets.ACCESS_TOKEN }}

确实这样做的，但是没有生效。
