### ISSUE TITLE
GitHub Actions `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by cclauss** [JamesIves/github-pages-deploy-action#1362]
The following appears in the GitHub Actions output of every job...
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Niek** [comment]
I had the same issue, but it disappeared when bumping the action to `v4.4.1`.

**Comment by JamesIves** [comment]
Closing as this is already fixed in newer versions.
