### ISSUE TITLE
Can't push folder in project

### ISSUE THREAD

**Issue by oliverunger** [JamesIves/github-pages-deploy-action#1427]
## Describe the bug
I would like to push a folder in my project that was generated by a maven build:
projectname (maven parent module)
--> model (maven child module)
----> src/main/resources/apidocs

## Reproduction Steps
I tried the following for the folder param with the following outcomings:
./model/src/main/resources/apidocs
Error: The directory you're trying to deploy named /home/runner/work/projectname/projectname/model/src/main/resources/apidocs doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗

../model/src/main/resources/apidocs
Error: The directory you're trying to deploy named /home/runner/work/projectname/model/src/main/resources/apidocs doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗

~/model/src/main/resources/apidocs
Error: The directory you're trying to deploy named /home/runner/model/src/main/resources/apidocs doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗

**Comment by JamesIves** [comment]
Similarly to https://github.com/JamesIves/github-pages-deploy-action/issues/1426, can you verify that these folders actually exist on the file system using `ls` or something else after the generation step occurs? This error is produced by this line: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/util.ts#L86-L90 which means Node cannot find the specified directory.

**Comment by oliverunger** [comment]
I dont understand it:
<img width="629" alt="image" src="https://github.com/JamesIves/github-pages-deploy-action/assets/97088274/4b614bf0-5de2-4794-850e-208f6f5ffad9">

Because in other github acions i can access the sources:
![image](https://github.com/JamesIves/github-pages-deploy-action/assets/97088274/50190502-ab53-49c1-995c-fafc63e25fe0)
