### ISSUE TITLE
Question about the CLEAN option

### ISSUE THREAD

**Issue by brockfanning** [JamesIves/github-pages-deploy-action#146]
My goal is to have the contents of BRANCH be completely replaced by the contents of FOLDER. Right now, it looks like the contents of FOLDER are copied into BRANCH, but existing stuff in BRANCH remains there. I thought that setting CLEAN to true might have done it, but it's not. I probably am misunderstanding what CLEAN is supposed to do, because I don't understand what "hashed files" means. Any guidance is welcome! Thank you!

**Comment by JamesIves** [comment]
The `CLEAN` option removes any files that are not currently in the current deployment. Hashed files are common in JavaScript projects, for instance you may have `File.js` that builds into `Fileabc123.js`. 

If `Fileabc123.js` exists in the destination branch, and the build job tries to commit `Fileefg456.js` it will remove `Fileabc123.js` as it doesn't exist in the current deployment. If the file names remain the same it will keep everything. It essentially keeps old reference files from building up within the deployment branch. 

Check out [this thread](https://superuser.com/a/156702) regarding the `--delete` flag as [it performs the same command](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/git.ts#L148).

**Comment by brockfanning** [comment]
Ok, got it,, thanks for the info!

**Comment by brockfanning** [comment]
Follow up correction - my statement above "but existing stuff in BRANCH remains there" was incorrect. I had forgotten to commit the change. So for me CLEAN is meeting my needs.

**Comment by JamesIves** [comment]
I don't know if the way the `CLEAN` option is explained is particularly clear. If you have any suggestions I'll certainly be happy to look at any PR's to the readme! 😄
