### ISSUE TITLE
The directory you're trying to deploy named /home/runner/work/RivioxTweaks/RivioxTweaks/dist doesn't exist.

### ISSUE THREAD

**Issue by vapmawtf** [JamesIves/github-pages-deploy-action#1505]
Run JamesIves/github-pages-deploy-action@4.1.4
  

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Error: The directory you're trying to deploy named /home/runner/work/RivioxTweaks/RivioxTweaks/dist doesn't exist. Please double check the path and any prerequisite build scripts and try again. ❗
Deployment failed! ❌

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/riviox/RivioxTweaks/actions/runs/7603764541/job/20705890239#step:5:11)-[11](https://github.com/riviox/RivioxTweaks/actions/runs/7603764541/job/20705890239#step:5:12)-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by JamesIves** [comment]
Found two issues:

- Looks like your Vite build script is erroring due to a syntax error, hence why there's no dist folder
- You are using an old version of this action which is why youre getting a deprecation warning
