### ISSUE TITLE
Sync local ms sql with remote mysql

### ISSUE THREAD

**Issue by stmawebapp** [JamesIves/github-pages-deploy-action#163]
**Sync local ms sql with remote mysql**

>
I'm developing a website with nodejs and mysql.

My client has got an MSsql server database in their buildings. The sql server DB is the main data source but it can not be used as the website's data source.
the website's mysql db is on onother server which can on cloud on the same building with different machine

So I have to regularly sync the two.

Any changes made by my client to their mssql db will be replicated to the website's mysql db, and changes to the mysql db (from users) must be replicated to the mssql server.

**Additional Comments**
Help will be much appreciated

**Comment by JamesIves** [comment]
This doesn’t seem relevant to this project. If you’re using it to transfer database information somehow you probably shouldn’t.
