### ISSUE TITLE
bug: 🐝 Cannot deploy from the root of the repo (?)

### ISSUE THREAD

**Issue by gaborcsardi** [JamesIves/github-pages-deploy-action#1694]
### Describe the bug

I have a build failing with
```
...
/usr/bin/git checkout -B github-pages-deploy-action/ayzsk9y5k
fatal: detected dubious ownership in repository at '/__w/cran-metadata/cran-metadata/github-pages-deploy-action-temp-deployment-folder'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/cran-metadata/cran-metadata/github-pages-deploy-action-temp-deployment-folder
Error: The process '/usr/bin/git' failed with exit code 128
Notice: Deployment failed! ❌
```
See https://github.com/r-hub/cran-metadata/actions/runs/11054520728/job/30711489044#step:5:63
Workflow file: https://github.com/r-hub/cran-metadata/blob/fc798e20c81ab6a347bf2ed19dd1226104e43ec0/.github/workflows/cran-update.yml

After the suggested fix: https://github.com/r-hub/cran-metadata/commit/04bbb0c9643728855b1e8d84371439e6e4c871a7
the build is green: https://github.com/r-hub/cran-metadata/actions/runs/11054605847/job/30711786063

Do you think this is an issue with the deploy action? 

### Reproduction Steps

Fork the https://github.com/r-hub/cran-metadata repo (all branches), enable actions, trigger the cran-update action on the `deploy-bug` branch.

### Logs

```shell
See above and at https://github.com/r-hub/cran-metadata/actions/runs/11054520728/job/30711489044#step:5:63
```

### Workflow

```yml
See above and at https://github.com/r-hub/cran-metadata/blob/fc798e20c81ab6a347bf2ed19dd1226104e43ec0/.github/workflows/cran-update.yml
```

### Additional Comments

Thanks for the great project, we use it A LOT.

**Comment by JamesIves** [comment]
Ah yeah this seems like a bug where we need to use the wildcard. I'll see about pushing up a patch version for this when I get a spare moment, thanks for reporting this!

**Comment by JamesIves** [comment]
A patch for this has been released as part of [v4.6.5](https://github.com/JamesIves/github-pages-deploy-action/releases/tag/v4.6.5), if you continue to see issues please let me know!

**Comment by gaborcsardi** [comment]
Thanks! However, no cigar just yet. It is still failing :( :
https://github.com/r-hub/cran-metadata/actions/runs/11073482646/job/30770120172#step:5:1

**Comment by JamesIves** [comment]
Can you provide the log files? I'm unable to access this

**Comment by gaborcsardi** [comment]
Ah, sorry, I deleted them accidentally. 

Here is another run: https://github.com/r-hub/cran-metadata/actions/runs/11074475445/job/30773335739#step:5:1

Actually, with 4.6.5 my workaround does not work, either:
https://github.com/r-hub/cran-metadata/actions/runs/11074419565/job/30773156777#step:5:2
https://github.com/r-hub/cran-metadata/actions/runs/11074419565/job/30773156777#step:6:1

**Comment by JamesIves** [comment]
Pushed up 4.6.6 which reverts this change, let me re-visit this and get you a beta version later today.

**Comment by sckott** [comment]
I don't know if this is related but this action just started failing for me without any changes in my repo, e.g. 

https://github.com/getwilds/registry/actions/runs/11075200637/job/30776070332#step:6:17

```
Error: File not found: '/home/runner/work/_actions/JamesIves/github-pages-deploy-action/v4.6.6/lib/main.js'
```

Same result with `@v4` and `@v4.6.6`
Happy to delete this comment if this is unrelated

**Comment by JamesIves** [comment]
It is unrelated, but that issue should be resolved now.

**Comment by JamesIves** [comment]
Possible fix for the above, please try pointing your workflow to `JamesIves/github-pages-deploy-action@releases/v4-dubious-bug`. I wasn't able to repro this myself, but this change adds the temp worktree directory to the safe list as directed by the error message itself.

**Comment by gaborcsardi** [comment]
Thanks, seems to work: https://github.com/r-hub/cran-metadata/actions/runs/11086265461/job/30803592562#step:5:1

**Comment by sckott** [comment]
@JamesIves thanks!

**Comment by JamesIves** [comment]
Great! Thanks for testing. I'll push a release up for this in the morning and ping the thread. Enjoy your weekend!

**Comment by JamesIves** [comment]
https://github.com/JamesIves/github-pages-deploy-action/releases/tag/v4.6.8
