### ISSUE TITLE
Document ACCESS_TOKEN required scope

### ISSUE THREAD

**Issue by hsz** [JamesIves/github-pages-deploy-action#18]
**Is your feature request related to a problem? Please describe.**

There is no information about the required scope for the `ACCESS_TOKEN`.

**Describe the solution you'd like**

Describe which parts of the scope are needed.

**Comment by JamesIves** [comment]
I added a note about it in the variables table. The actual scope type will depend on the type of repository the action is being used in.

Keep in mind that once #13 merges the access token will be somewhat obsolete (although it will still work for redundancy) as the `GITHUB_TOKEN` is correctly scoped to the repository which invoked the action.
