### ISSUE TITLE
Publish As Library

### ISSUE THREAD

**Issue by XAMPPRocky** [JamesIves/github-pages-deploy-action#180]
**Is your feature request related to a problem? Please describe.**

I'd like to use this action inside of another action, as a lot of my deployments are using the same tools to create the deployment, so it would be nice if I could have a single action that builds and deploys.

**Describe the solution you'd like**

 The only way I know how to share code between actions is to publish a library version of the package to npm. If there are other alternatives that would be great.

**Comment by JamesIves** [comment]
It's already on the npm registry, but I never added the `npm publish` workflow to the repository actions so it's been stale for a while. I just made a release that adds this workflow so it should now always be in sync with the version on the GitHub marketplace: https://www.npmjs.com/package/github-pages-deploy-action

I've never tested using this in another project, but _technically_ you should be able to do the following:

`install deploy from 'github-pages-deploy-action'`

If you run into any issues please feel free to report them here. I may need to make a few adjustments for this to get consumed correctly by another library.

**Comment by XAMPPRocky** [comment]
@JamesIves The problem with the current setup is twofold, because the `"main"` is `"lib/main.js"` and in `main.ts` you export and then immediately call main so importing the package causes side-effects. It would be better if there was second file `src/lib.ts` which became the package `"main"` that only exported the functions, and then import and call them in `main.ts`.

https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/main.ts#L20

The second problem is that all of the configuration is done through `src/constants.ts` that pulls in from the environment. While this isn't a deal breaker it'd be nice to be able pass the configuration explicitly as an object.

**Comment by JamesIves** [comment]
Yep makes sense, this wasn’t really accounted for when I wrote this. I’m happy to make these changes today if you’d be willing to review them?

**Comment by XAMPPRocky** [comment]
@JamesIves I'd be happy to! 😄

**Comment by JamesIves** [comment]
Here's the PR for the corrected module exporting; https://github.com/JamesIves/github-pages-deploy-action/pull/181

You should be able to pull it down and do `yarn link` to test it out locally. I didn't make the configuration an argument though, I'm a little concerned about implementing possible security holes as people will need to pass an access token into this, and it may cause GitHub to expose that at runtime.

**Comment by XAMPPRocky** [comment]
@JamesIves I would say leaving the github token as something that is picked up from the environment, and documenting that would be a fine compromise. I'm mainly concerned with the configuration options, the token it's one variable I can easily set and re-export in the environment as opposed to having 14.

**Comment by JamesIves** [comment]
I'm fine with that - I've updated the PR. Both `accessToken` and `gitHubToken` get re-assigned at runtime in `lib.ts` to make sure they are properly secured.
