### ISSUE TITLE
[wiki] adding the private key to the secrets in PEM format

### ISSUE THREAD

**Issue by vighnesh153** [JamesIves/github-pages-deploy-action#184]
**Describe the bug**

> Please provide a clear and concise description of what the bug is.

In the wiki, when we add the private SSH key to the secrets, it is not accepted as is.
Check this issue: https://github.com/webfactory/ssh-agent/issues/9

Before adding the private key in the secrets, it needs to be converted to PEM format. I 
tried adding it without converting, the `webfactory/ssh-agent` installation threw an error saying that it is in invalid format.

I request you to add this in the wiki.

**Comment by JamesIves** [comment]
I'm not sure that the wiki for this action would be the right place for this. While that ssh agent action is a good one to use, you can technically use any one you like so long as it establishes the key relationship before the deployment steps run.
