### ISSUE TITLE
Deployment to different repo doesn't seem to work

### ISSUE THREAD

**Issue by carmineos** [JamesIves/github-pages-deploy-action#191]
**Describe the bug**

I'm using REPOSITYORY_NAME but it keeps deploying to the same repo, maybe I'm doing something wrong?
https://github.com/carmineos/BlazorApp/actions/runs/48714668/workflow

**Comment by JamesIves** [comment]
You have a typo: `REPOSITYORY_NAM` -> `REPOSITORY_NAME`

**Comment by carmineos** [comment]
omg 🤦‍♂
i've fixed it but now i have this https://github.com/carmineos/BlazorApp/runs/482299655#step:5:15

**Comment by JamesIves** [comment]
No problem, if you're still having problems try toggling `DEBUG` to true so you can get visibility on what git command is failing.

**Comment by carmineos** [comment]
Without using `persist-credentials: false` i get [this](https://github.com/carmineos/BlazorApp/runs/482373136?check_suite_focus=true#step:5:66)
```
remote: Permission to carmineos/carmineos.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/carmineos/carmineos.github.io.git/': The requested URL returned error: 403
```

While if I specify it I get [this](https://github.com/carmineos/BlazorApp/runs/482357357?check_suite_focus=true#step:5:66)

```
fatal: could not read Password for 'https://***@github.com': No such device or address
```

The scope of the ACCESS_TOKEN is `repo` only with everything on.

**Comment by JamesIves** [comment]
Give this permission scope a try;

![CE07A81A-BC78-43E5-BF8E-6671F75BB10A](https://user-images.githubusercontent.com/10888441/75785216-5e97aa80-5d31-11ea-87ae-a065b15ae656.jpeg)

I’ve not encountered that error before but I can only assume it’s something to do with the scope of your access token.

**Comment by carmineos** [comment]
So turns out the problem was the ACCESS_TOKEN itself, I've just created another one and now everything works, the only required scope was `repo`

**Comment by JamesIves** [comment]
Great! I'm glad it works.

**Comment by carmineos** [comment]
Thanks!
