### ISSUE TITLE
Host key verification failed when using a SSH deployment key

### ISSUE THREAD

**Issue by dev-zero** [JamesIves/github-pages-deploy-action#199]
**Describe the Issue**

The deployment fails with a `Host key verification failed` (using a SSH deployment key). We need persistent credentials for submodule checkout to work (and would like to keep using `v2` of the checkout action, but comparing to other issues it does not seem to be related, or does it?

**Logs**

https://github.com/cp2k/dbcsr/runs/497387980?check_suite_focus=true

**Comment by dev-zero** [comment]
sorry, doesn't seem to be a problem with your action, but rather [this issue with the ssh-agent](https://github.com/webfactory/ssh-agent/issues/20)

**Comment by JamesIves** [comment]
There's several alternative actions out there that will setup the ssh agent, so long as it sets the key in the environment then you're good to go. I felt this action would be doing too much if it set the keys its self.
