### ISSUE TITLE
Getting error code 128

### ISSUE THREAD

**Issue by antoniogamiz** [JamesIves/github-pages-deploy-action#216]
**Describe the Issue**

Every time I get to the deploy job it does not finish, it returns error code 128 while configuring git.

**Logs**

- Workflow file: [link](https://github.com/antoniogamiz/cuarto-segundo-cuatrimestre/blob/master/.github/workflows/deploy-latex.yml)
- Logs: [link](https://pipelines.actions.githubusercontent.com/Sk5jT0LgpRdq8vxkQPMAbOfKaHw074k25ADRcDZcFse253kbdy/_apis/pipelines/1/runs/8/signedlogcontent/13?urlExpires=2020-03-27T19%3A03%3A28.5283987Z&urlSigningMethod=HMACV1&urlSignature=GVHPXnzmUOq3RSFvunr%2BgBg%2FObnU1vZ%2BW3KrE%2F0KHqE%3D)

**Comment by JamesIves** [comment]
You enable the debug mode? Attach `DEBUG: true` to the `with` configuration.

**Comment by antoniogamiz** [comment]
Done.

**Comment by antoniogamiz** [comment]
I also changed action version to 3.4.2 because of https://github.com/JamesIves/github-pages-deploy-action/issues/111

**Comment by JamesIves** [comment]
I was unable to reproduce this error myself, but I may have come up with a solution that will work should this error be encountered. Can you try changing the action version to the following and try re-running your build again? `JamesIves/github-pages-deploy-action@releases/v3-test`

**Comment by JamesIves** [comment]
This is occurring because you're missing a step in your deploy workflow. You need to checkout the changes or it won't know what to track. You have it in your other step:

```
- name: Checkout 🛎️
   uses: actions/checkout@v2
    with:
          persist-credentials: false

```

**Comment by antoniogamiz** [comment]
Oh, you're right. Thanks a lot! I though the checkout step needed to be done only at the beginning ( I was misled by an example in github documentation), sorry for the trouble and thanks for the help :).
