### ISSUE TITLE
Could not find file .bin/semver

### ISSUE THREAD

**Issue by tlienart** [JamesIves/github-pages-deploy-action#228]
Hello, I've been using this GA a fair bit recently (thanks!) without issue up to a few minutes ago when the workflow failed with

```
Current runner version: '2.165.2'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
Download action repository 'webfactory/ssh-agent@v0.2.0'
Download action repository 'actions/setup-python@v1'
Download action repository 'julia-actions/setup-julia@v1'
Download action repository 'JamesIves/github-pages-deploy-action@releases/v3'
##[error]Could not find file '/home/runner/work/_actions/_temp_ \ 
a689c3df-959c-4ba7-bd79-e427cc02b22b/_staging/ \ 
JamesIves-github-pages-deploy-action-c34cb8d/node_modules/node-notifier/node_modules/.bin/semver'.
```

(https://github.com/JuliaLang/www.julialang.org/runs/548737314) 

Any idea what may cause the issue? I've tried re-running the workflow thinking it could be a glitch but it didn't help. Thanks in advance

**Edit**: adjusted the output for readability

**Comment by tlienart** [comment]
Ok actually I tried one more time and the workflow now runs fine (🤷‍♂). I'll close the issue. Apologies for the spam.

**Comment by JamesIves** [comment]
@tlienart Sorry about that, I think what happens here is that GitHub is looking for a specific version of these files, but as they were removed from the deployment branch it needs a couple of minutes to get back to speed and find the new versions of them. I see this problem every time I release (which is what I'm doing at the moment) in my integration tests. After a couple of retries it's usually back to normal. 

I think you can avoid this by specifying an exact version number, for example: `uses: JamesIves/github-pages-deploy-action@3.4.2`

**Comment by tlienart** [comment]
Great, thanks, I'll do that
