### ISSUE TITLE
Feature request: preserve history of gh-pages

### ISSUE THREAD

**Issue by giovannibonetti** [JamesIves/github-pages-deploy-action#23]
**Is your feature request related to a problem? Please describe.**

In my company we have recently switched from Wordpress to Jekyll for a series of reasons, and one of them was to have version control of our blog / homepage / comercial website.

We have enjoyed using your action in the last step of our build pipeline, however we wanted to preserve the history of gh-pages between deploys and ultimately switched to [another Github Action](https://github.com/marketplace/actions/gh-pages-deploy) that [does that](https://github.com/Cecilapp/GitHub-Pages-deploy/blob/master/entrypoint.sh#L31) and is smart enough to [avoid a deployment if nothing changed](https://github.com/Cecilapp/GitHub-Pages-deploy/blob/master/entrypoint.sh#L50-L51).

**Describe the solution you'd like**

Since your action is actively maintained, I though you might be interested in adding that funcionality [based on the other mentioned action](https://github.com/Cecilapp/GitHub-Pages-deploy/blob/master/entrypoint.sh) that is less maintained.

**Additional Comments**

The end result of having full version control of gh-pages branch is great! We can even compare visually the history of our blog locally by moving between commits.

**Comment by JamesIves** [comment]
This makes sense to me. 

I think preserving the git history will require re-working the use of `git subtree`. If you have a preferred method of pushing the commits that will preserve the history I'm more than happy to review any PR's.

**Comment by giovannibonetti** [comment]
Thanks for the encouragement!

I could do a PR replacing your `entrypoint.sh` [by the other one](https://github.com/Cecilapp/GitHub-Pages-deploy/blob/master/entrypoint.sh) but I guess that's probably not what you want. I created this issue to mention an alternate solution to the same problem, but I'm not confident enough to put both solutions side by side to compare each other.
Since this is a very small project and nobody cares about creating a test suite for bash scripts I think it would be a waste of time for both of us to argue about 10-20 of lines of bash script to decide how to merge the current solution with the proposed one. I'm afraid of breaking something that works in your script (by the way, if you are serious about bash you might be interested in the [unofficial strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/).

Here in my company we are using the other action, but if you like the idea I think it's up to you to decide which part of the other workflow you want to use and which part you want to keep as it is. I'm not trying to put any pressure on you, my checkbox is already ticked. My objective when I opened this issue was to contribute to your project by sharing another approach that has worked well for us. But I'm not taking the risk of breaking a bash script without automated tests. Unfortunately I can't help you with this.

If that disappoints you then just close this issue, no hard feelings.

Thanks again for your time.

**Comment by jeoy** [comment]
@giovannibonetti  check this action [demo](https://github.com/jeoy/github-deploy-actions/commits/gh-pages), it can preserve history of gh-pages.

**Comment by giovannibonetti** [comment]
Nice work, @jeoy!

I think it would be nice to add an example YML workflow in the README to show it should be used.

**Comment by jeoy** [comment]
@giovannibonetti  good advice, tks
