### ISSUE TITLE
There is nothing to commit. Exiting early...

### ISSUE THREAD

**Issue by zimmicz** [JamesIves/github-pages-deploy-action#230]
I'm trying to run `yarn build` on my `master` branch and deploy the contents of resulting `dist` folder to the `gh-pages` branch. However, I always get the empty commit to `gh-pages`.

**Logs**
The debugged deployment log is available at https://pipelines.actions.githubusercontent.com/2lt5Dfrwx72LwrtzWCZ8ubuhqksxPCmCHel2gEmYuNG0DNSuRi/_apis/pipelines/1/runs/36/signedlogcontent/3?urlExpires=2020-04-01T17%3A28%3A06.6105530Z&urlSigningMethod=HMACV1&urlSignature=kfxVO1GHvjzy5BwxZwuiSkAkj1q8iUG5HnlzBzOSULg%3D. The deployment step starts at `2020-04-01T17:25:44.6369644Z` timestamp.

I'm using almost identical workflow to the example one. It's available at https://github.com/cartostory/cartostory-frontend/blob/master/.github/workflows/deploy.yml.
```
The `dist` folder is ignored in `.gitignore`, but even without that line I can't make it work. What am I doing wrong?

**Comment by zimmicz** [comment]
Omg, was using `v3-test` instead of `v3` release of the action :D

**Comment by JamesIves** [comment]
Just restored `v3-test` to be inline with `v3`. Probably best to switch anyway as that's the stable branch! 👍
