### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by sarink** [JamesIves/github-pages-deploy-action#231]
When using `actions/checkout@v1`, I receive the following error from this action:
```
 Publish gh-pagess
Deployment Failed ❌
Run JamesIves/github-pages-deploy-action@releases/v3
Checking configuration and starting deployment… 🚦
Deploying using Access Token… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment Failed ❌
```

If I switch to `actions/checkout@v2`, everything works fine. However, that breaks several other actions I use, and it's not feasible to upgrade them all at this time.

Shouldn't this lib be backwards-compatible with both? If not, can I downgrade to a version of it that is/which one would that be?

**Comment by JamesIves** [comment]
Can you post your workflow?

**Comment by sarink** [comment]
Hmm, you're right @JamesIves ... it looks like the real problem is that I'm using this in conjunction with https://github.com/phips28/gh-action-bump-version/blob/master/index.js, which automatically adds a git commit. It appears that this process is what breaks `gh-deploy-pages` 🤔

**Comment by JamesIves** [comment]
Can I see your workflow please? I can't really assist without the full context. In what order are you calling this? 

You can also enable debug mode by setting `ACTIONS_STEP_DEBUG` to `true` within the `Settings/Secrets` menu.

**Comment by sarink** [comment]
Sure, it's here: https://github.com/sarink/react-file-drop/blob/master/.github/workflows/ci.yml

**Comment by sarink** [comment]
I believe this is something to do with the gh-action-bump-version code adding a commit in the checkout v1 detached head state [source](https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L49), what I don't understand is why `github-pages-deploy-action` has a problem with this? I switched back to `@3.1.5` version of this (because I noticed that's right before checkout@v2 support was added, I guess it doesn't matter though) and _now_ I am getting a `Permission denied` error, not just a `128`. I'll upgrade to the latest version and set the debug to true and post some new logs in a bit.

**Comment by sarink** [comment]
https://github.com/sarink/react-file-drop/runs/558418298?check_suite_focus=true
```
##[debug]Evaluating condition for step: 'Publish gh-pages'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Publish gh-pages
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.GH_PERSONAL_ACCESS_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GH_PERSONAL_ACCESS_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run JamesIves/github-pages-deploy-action@3.4.6
Checking configuration and starting deployment… 🚦
Deploying using Access Token… 🔑
Configuring git…
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/react-file-drop/react-file-drop/.git/
/usr/bin/git config user.name sarink
/usr/bin/git config user.email sarink87@gmail.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin https://***@github.com/sarink/react-file-drop.git
/usr/bin/git fetch
From https://github.com/sarink/react-file-drop
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      master     -> origin/master
 * [new branch]      v2         -> origin/v2
 * [new branch]      v3         -> origin/v3
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads https://***@github.com/sarink/react-file-drop.git gh-pages | wc -l
355d0c2ec926553d626b60038653498162ee3429	refs/heads/gh-pages
/usr/bin/git checkout --progress --force afae7e8c5ab199e777c8029f5c390e1ffaa64388
Note: switching to 'afae7e8c5ab199e777c8029f5c390e1ffaa64388'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at afae7e8 Update github-pages-deploy-action version
/usr/bin/git fetch https://***@github.com/sarink/react-file-drop.git
From https://github.com/sarink/react-file-drop
 * branch            HEAD       -> FETCH_HEAD
/usr/bin/git worktree add --checkout gh-action-temp-deployment-folder origin/gh-pages
Preparing worktree (detached HEAD 355d0c2)
HEAD is now at 355d0c2 Deploying to gh-pages from  3c246eca0252556889f451bb3cb4f9b11803e5e7
/usr/bin/rsync -q -av --progress demo/dist/. gh-action-temp-deployment-folder/. --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
/usr/bin/git status --porcelain
 D index-695757.bundle.js
 M index.html
?? index-2bc8c1.bundle.js
/usr/bin/git add --all .
/usr/bin/git checkout -b gh-action-temp-deployment-branch
fatal: cannot update the ref 'refs/heads/gh-action-temp-deployment-branch': unable to append to '/home/runner/work/react-file-drop/react-file-drop/.git/logs/refs/heads/gh-action-temp-deployment-branch': Permission denied
/bin/rm -rf gh-action-temp-deployment-folder
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment Failed ❌
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Publish gh-pages
```
Any ideas @JamesIves ? Thanks for your help :)

**Comment by JamesIves** [comment]
Nothing is striking me as wrong here. I'm guessing another action is conflicting with the git tree and it's causing some problems. Perhaps you could run the deployment in a separate job, or run `actions/checkout` a second time?

**Comment by sarink** [comment]
I wanted to bump the version number before I deployed gh-pages, but the very act of bumping the version messes with the git tree in such a way that this fails.

Do you have any idea with [this code](https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L49) would be interfering with the gh-deploy?

**Comment by JamesIves** [comment]
The error you're getting looks like it's coming from an attempt to write to the `.git` directory. I'm not sure why this is happening, but you can either try running chmod on that directory prior to the deployment run, or try deleting `.git` or/and running the checkout step again prior to deploying.

**Comment by JamesIves** [comment]
Any luck?

**Comment by csi-lk** [comment]
To add to the conversation am getting the same error with a new repo

```
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
```

Build is here: https://github.com/csi-lk/csi.lk/runs/571098491?check_suite_focus=true

Workflow: https://github.com/csi-lk/csi.lk/blob/537663b7611341e35b4a9e78ced53778cbb63eef/.github/workflows/master.yml

I'll start trying to debug see where I get

**Comment by sarink** [comment]
I wasn't able to figure it out. I settled for doing this in a separate step before bumping the package version, which means I'm always technically deploying to gh-pages with the package.json showing that it's 1 version behind (even though it's not), and I have to build my project in ci twice, neither of which are ideal. Perhaps I'll revisit this someday.

**Comment by QuinnBast** [comment]
Also running into this issue and tried to do a number of suggested steps like installing `rsync` and using `checkout/v2` but nothing has resolved this.

Build: https://github.com/Subterfuge-Revived/Remake-Core/runs/609400699

Workflow: https://github.com/Subterfuge-Revived/Remake-Core/blob/github-actions/.github/workflows/DeployRelease.yml#L57

**Comment by emma-sax4** [comment]
I'm running into a similar issue. I'm not doing any type of package bump at all, but I did go back to `actions/checkout@v1` so that it wouldn't rewrite a bunch of `<updated>` and `dateModified` information in the HTML files.

Build: https://github.com/emma-sax4/emma-sax4.github.io/runs/673287341?check_suite_focus=true

Workflow: https://github.com/emma-sax4/emma-sax4.github.io/blob/fe476855b336f5c3e8d98da8f659d913355e9af9/.github/workflows/test-and-deploy.yml#L29-L36

**Comment by JamesIves** [comment]
You are using the GitHub token in the wrong param, change `ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}` to `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`. The action builds a git path but they are slightly different depending on the token you use.

Please open an issue if you're experiencing any further issues.
