### ISSUE TITLE
Action's Docker Container will sometimes "exit early"

### ISSUE THREAD

**Issue by Rangoric** [JamesIves/github-pages-deploy-action#24]
**Describe the bug**

I use this in conjunction with Gatsby to generate a fairly large (well markdown file size) github pages website.

The build itself works fine, and it will suddenly exit with a 128 while pushing files to github.

**Reproduce**

It's only sometimes after I push changes. It's been every other run so far. I have logs, but they don't have what I need to diagnose.

**Expected behavior**

To not get cut off while uploading.

**Screenshots**

https://github.com/Rangoric/rangoric.github.io/actions

The repo is public, I am not sure if actions are readable by the public. If not, let me know.

**Additional Comments**

I don't think this is an issue on your end, but I've seen it twice, and the logs never give me what the actual issue is, it just stops mid push so am hoping for ideas.

Also, this is a personal project so not critical, but also means I can test / help with any changes needed to troubleshoot this. If the site goes down I'm the only one that would notice.

When it works, it works perfectly.

**Comment by Rangoric** [comment]
Just read the logs more carefully looking for anything and saw:

`fatal: write failure on 'stdout': Resource temporarily unavailable` at https://github.com/Rangoric/rangoric.github.io/commit/61a27286df73ca747a81585c0771acf817a482df/checks#step:4:3281

It was in the middle of the log so not easy to spot.

**Comment by JamesIves** [comment]
Can you give this branch a try? `uses: JamesIves/github-pages-deploy-action@debug`

I wonder if like you said it's doing this because it's flooding the logs with so many files. In that branch I've switched the push command into silent mode so that shouldn't occur anymore.

**Comment by Rangoric** [comment]
I put that in, I'm running it once with that, and later after work I will switch gatsby to not log anything also, and I'll report back what happens.

**Comment by Rangoric** [comment]
With that change I got the error again, but it wasn't being quiet. I'll see what I can do on my side to nuke the log, because it's thousands of lines.

https://github.com/Rangoric/rangoric.github.io/commit/85e0d89240e372d9ab2814c12d4bc8ac2f09a514/checks

**Comment by JamesIves** [comment]
Ah my apologies, I put the quiet flag in the wrong spot. Can you try it again?

**Comment by Rangoric** [comment]
I've gone 3 or 4 builds with no issue. 

I will still try to quiet down Gatsby but it might be the speed at which the log get written to. Gatsby is long but does it over time (usually) while the github pages push was real fast all at once.

I will try and quiet Gatsby, but as I said, no issues for a few builds in a row.

**Comment by JamesIves** [comment]
That's great to hear. I'll put a patch up for the quiet commit logs later today.

Feel free to re-open this issue if you encounter this same error again. Thanks for the report!

**Comment by JamesIves** [comment]
@Rangoric I've pushed the change to master, you'll want to switch your action back to using the `@master` version to prevent build failures.

Thanks again!
