### ISSUE TITLE
Trouble publishing to other repo

### ISSUE THREAD

**Issue by IronSean** [JamesIves/github-pages-deploy-action#243]
**Describe the Issue**

I'm trying to publish from MyOrg/MyRepo to MyOrg/myorg.github.io and can not get it to work. Publishing to a local `gh-pages` branch worked fine, but you can't use a `gh-pages` branch for an org website.

**Logs**

```
##[debug]Evaluating condition for step: 'Deploy 🚀'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy 🚀
##[debug]Loading inputs
##[debug]Evaluating: secrets.SEAN_DEPLOYMENT_PAT
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'SEAN_DEPLOYMENT_PAT'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run JamesIves/github-pages-deploy-action@releases/v3
Checking configuration and starting deployment… 🚦
Deploying using Access Token… 🔑
Configuring git…
/usr/bin/git init
Reinitialized existing Git repository in /home/runner/work/TorqIT-next/TorqIT-next/.git/
/usr/bin/git config user.name IronSean
/usr/bin/git config user.email seanrmackay@gmail.com
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/TorqIT/torqit.github.io.git
/usr/bin/git fetch
remote: Repository not found.
```

**Additional Comments**

Here is my workflow
```
name: Node.js CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run export
      env:
        CI: true
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.SEAN_DEPLOYMENT_PAT }}
        REPOSITORY_NAME: TorqIT/torqit.github.io
        BRANCH: master # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
```

**Comment by JamesIves** [comment]
What permissions are you providing the access token? It's likely that your personal access token is not scoped high enough which is why you're seeing this error. You'll probably need to provide it full admin privileges, and you yourself will need to be an owner of the org. Deploying cross-repo within an organization isn't something I've personally tested.

<img width="771" alt="Screen Shot 2020-04-08 at 9 30 18 AM" src="https://user-images.githubusercontent.com/10888441/78789748-940c6500-797b-11ea-88fb-bc6d0a5edfe8.png">

**Comment by IronSean** [comment]
That's a good though, I had only given the Repo poermissions on the assumption that "This is a repository that my user account is allowed to write to", but I guess things are rarely that simple.
![image](https://user-images.githubusercontent.com/1960190/78798062-edca5a80-798e-11ea-96bb-55ebe0aa396f.png)

I'm going to test that now. Luckily I _am_ the owner of the org, so that shouldn't be a problem.

I do wish github allowed you to use a `gh-pages` branch for personal/org websites instead of forcing master... then this would have just worked from the start 🤷‍♂

**Comment by IronSean** [comment]
Unfortunately even with full admin:org permissions it still doesn't seem to work. This might be more an issue with Github than your action unfortunately.

**Comment by JamesIves** [comment]
Try adding `persist-credentials: false` in the actions/checkout step. I'm guessing it's trying to deploy with the GitHub token as it writes it to the git config on init. If you want to deploy with an access token which has the correct permission scope outside of the existing repo you'll need to set this config. 

```
- uses: actions/checkout@v2
   with:
      persist-credentials: false
```

**Comment by IronSean** [comment]
That did it! 

I skimmed the first two thirds of the example assuming they were generic checkout and build steps and didn't read that comment. Thank you for your help!

Now I just need to inject a `.nojeckyll` file and I think I'm in business.

**Comment by JamesIves** [comment]
You should be able to commit that directly to the branch, the history will remain in tact so it won’t need to be written every time you make a push. 

Glad it worked!
