### ISSUE TITLE
[error]The process '/bin/chmod' failed with exit code 1

### ISSUE THREAD

**Issue by thomasmarkiewicz** [JamesIves/github-pages-deploy-action#247]
**Describe the Issue**

The workflow job in question builds and deploys a flutter web app to the GitHub pages, on gh-pages branch. I've tried several different variations but cannot figure out how to make it work successfully.  I'm not sure at this point if it is a bug or something I'm misconfiguring? 

I'm currently getting this error and I don't know what to do with it:

```
[error]The process '/bin/chmod' failed with exit code 1
```

**Logs**

https://github.com/thomasmarkiewicz/bodysculpting/runs/579246467?check_suite_focus=true

```

Run JamesIves/github-pages-deploy-action@releases/v3
4s
Deployment Failed ❌
Run JamesIves/github-pages-deploy-action@releases/v3
Checking configuration and starting deployment… 🚦
Deploying using Access Token… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
There is nothing to commit. Exiting early… 📭
##[error]The process '/bin/chmod' failed with exit code 1
Deployment Failed ❌
```

**Comment by JamesIves** [comment]
Fortunately this is part of the tear down task so it shouldn't actually cause problems with the deployment process so long as it's the last action executed in the workflow.

I'm going to migrate the `rm -rf` part of this task to use the actions toolkit command as it's more mature and built specifically for this, hopefully that will eliminate the need to chmod the directory. Standby for a prompt update!

**Comment by JamesIves** [comment]
https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.4.8
