### ISSUE TITLE
Can't deploy: rsync fails with code 23

### ISSUE THREAD

**Issue by davidstellini** [JamesIves/github-pages-deploy-action#261]
Hi,

I have a strange error using the action:
`##[error]The deploy step encountered an error: The process '/usr/bin/rsync' failed with exit code 23 ❌
`

I added this step, with no luck,
      - name: Install rsync
        run: |
          sudo apt-get update && sudo apt-get install -y rsync

The build is here: 
https://github.com/davidstellini/keyscroll/runs/618356474
Workflow is here:
https://github.com/davidstellini/keyscroll/blob/5a4c6260105bee1bfacb18d95a0403c01e3f336c/.github/workflows/main.yml
Do you have any ideas what I can try out?

**Comment by davidstellini** [comment]
If it helps anyone else - Seems like the build was failing silently, it didn't find the folder, resulting in this error.

**Comment by JamesIves** [comment]
I can see what I can do about making that error more visible

**Comment by jerrychong25** [comment]
> If it helps anyone else - Seems like the build was failing silently, it didn't find the folder, resulting in this error.

Thanks. 

In my case, I missed out `npm run build` so it cant find the /dist folder and throws this error.

**Comment by JamesIves** [comment]
In newer versions there is an error that will let you know that the distribution folder cannot be found. Depending on which version you're using you may need to follow the README again as there's been some breaking changes between 1, 2 and 3.
