### ISSUE TITLE
Support target (sub)folders

### ISSUE THREAD

**Issue by Meemaw** [JamesIves/github-pages-deploy-action#267]
**Is your feature request related to a problem? Please describe.**

Trying to set a nested `TARGET_FOLDER` (e.g. `app/rev/10`) seems to fail with `rsync` error -- probably due to some missing option to create path to folder.

**Describe the solution you'd like**

It should be possible to deploy to subfolders.

**Comment by JamesIves** [comment]
Can you provide an example of the workflow configuration you're using?

**Comment by JamesIves** [comment]
Managed to repro this; this will be pushed up in `3.4.9`.
