### ISSUE TITLE
Clean up destination branch before copying new files

### ISSUE THREAD

**Issue by aronnebrivio** [JamesIves/github-pages-deploy-action#277]
It seems that the action currently simply copies the modified files to the target branch, without removing the files no longer present among those to be deployed.
This ensures that files like `CNAME` and `.nojekyll` are not removed, but neither does it remove the "junk" left over from previous deployments.

It would be nice if the script had a configurable whitelist of files not to overwrite or remove and keep only those, cleaning everything else.    
Or maybe this possibility is already there and I can't find it?

Thanks

**Comment by JamesIves** [comment]
Have you look into `CLEAN` and `CLEAN_EXCLUDE`? Both of those configuration options do exactly what you're describing and are available in version 3: https://github.com/JamesIves/github-pages-deploy-action#optional-choices

**Comment by aronnebrivio** [comment]
@JamesIves oh sorry my bad, didn't see them, I'm closing the issue 😅
Thank you for your work, beautiful script!
