### ISSUE TITLE
Add JavaScript to the name

### ISSUE THREAD

**Issue by schrej** [JamesIves/github-pages-deploy-action#28]
**Is your feature request related to a problem? Please describe.**
Currently, this action allows to run JavaScript build comands during the deployment. In my opinion, this action should rather just focus on actually deploying. If it's necessary to build something in the process, that should be an extra step.

**Describe the solution you'd like**
No longer use the node:10 docker container. In fact: don't use docker at all. Just run the necessary git commands to push the changes to the specified branch.

**Additional Comments**
This change would also allow to have a single action that builds every time, but only deploys when the branch is `master` by using [`jobs.<job_id>.steps.if`](jobs.<job_id>.steps.if).

**Comment by schrej** [comment]
Well, derp. Apparently there are multiple other actions that do exactly that. Maybe it would be a good idea to add JavaScript to the name of the action, so it's clearer.

**Comment by JamesIves** [comment]
It's mentioned in the first paragraph of readme, but I'd like to avoid adding it into the name of the action as the build script step is technically optional so it should be suitable for most use cases.
