### ISSUE TITLE
Support for overriding .gitignore

### ISSUE THREAD

**Issue by OR13** [JamesIves/github-pages-deploy-action#281]
I want to add a dist folder to `.gitignore`, but then deploy that folder using this action.

Related: https://stackoverflow.com/questions/48588908/deploying-ignored-dist-folder-to-github-pages

Right now, it won't deploy the folder if its git ignored.... this is causing people to commit the dist folder, making our PR review process terrible.

**Comment by JamesIves** [comment]
What does your workflow and `.gitignore` file look like?

**Comment by OR13** [comment]
sorry, I hate when people do that :)

https://github.com/decentralized-identity/sidetree

^ we are building a spec, and then using this action to deploy it to the gh-pages branch.

Its my understanding that `.gitingore` is respected by this action, so while developing locally, you would build the spec, and preview it, and then want to commit all the changes except for the `dist` folder... but in CI, you would want to push the `dist` folder to `gh-pages` branch.

**Comment by JamesIves** [comment]
I see you have `.` as the folder name, is your intention to deploy the entire root of the repository including the `dist` folder? This doesn't look correct to me as there's no index file: https://github.com/decentralized-identity/sidetree/tree/gh-pages

I think probably what you want to do is set `FOLDER` to `dist` which will work as that folder itself doesn't have a `.gitignore` file in it. 

If you actually do want to deploy the root directory then I'd suggest creating another script [here](https://github.com/decentralized-identity/sidetree/blob/master/package.json#L45) which builds your project and also removes the `.gitignore` file, and then run that pre-deployment script before this action runs.

**Comment by OR13** [comment]
@JamesIves thanks I agree with your points about hosting, the issue is likely related to workarounds for this spec tool: https://github.com/csuwildcat/spec-up

I will see if we can get the spec to be better isolated, so we don't need to deploy from a folder which contains a `.gitignore`.

thanks for your comments, and your awesome github action!

Feel free to close this, I think your suggestions are better than making any changes to your action.
