### ISSUE TITLE
Fix markdown table in readme

### ISSUE THREAD

**Issue by MichaelCurrin** [JamesIves/github-pages-deploy-action#286]
Caused by the change in #285, the table is badly formatted and displays as text:

```
| Key | Value Information | Type | Required | | -------------- | -----------------------
```

**Comment by MichaelCurrin** [comment]
BTW in case it helps, VS Code has Markdown All In One extension which automatically formats tables and adjusts with for you to keep columns consistent

**Comment by JamesIves** [comment]
Sorry I must have missed this issue- this was fixed.
