### ISSUE TITLE
Improve commit message

### ISSUE THREAD

**Issue by brendanator** [JamesIves/github-pages-deploy-action#29]
**Is your feature request related to a problem? Please describe.**

The commit messages look like `Deploying to gh-pages - 12:46:39`. The time is not useful as commits already have a time associated with them and the time is wrong for timezones that are non-GMT. 

**Describe the solution you'd like**

Ideally the commit message would reference the commit from the source branch:
`git commit -m "Deployed from $BASE_BRANCH - $GITHUB_SHA"`

**Comment by JamesIves** [comment]
Thanks! This has been pushed to the `master` branch.
