### ISSUE TITLE
Action doesn't clean up deleted files/directories?

### ISSUE THREAD

**Issue by emma-sax4** [JamesIves/github-pages-deploy-action#300]
**Describe the Issue**
I used this GH action to deploy some code to my `master` branch on my site. The code that was deployed should've deleted a couple of directories that my site no longer needed (I just moved some directories around). This action properly made the "new" directories, but never deleted the "old" ones. Essentially, the action didn't seem to clean up deleted files/directories properly.

Here's the action deploy from this action: https://github.com/emma-sax4/emma-sax4.github.io/commit/7ec1712671339f342549bf73866cdac8613ee98b
Here's the commit I had to make to clean up afterwards: https://github.com/emma-sax4/emma-sax4.github.io/commit/dd1710df255b8e0c94b5027cdebe7afe45e4e3ab

Is this what the `clean` argument is supposed to be used for? Or is this working how it's designed, or is this a bug?

**Logs**
Here's the log from the workflow run: https://github.com/emma-sax4/emma-sax4.github.io/runs/683553763?check_suite_focus=true
Here's my workflow (my fork of the action is basically just `releases@v3`): https://github.com/emma-sax4/emma-sax4.github.io/blob/3183868212bc56b17eaeeabce43081ea766ecb58/.github/workflows/release.yml#L40

**Additional Comments**
Thanks again for the help. This action is beautiful... I just want to make sure I'm understanding it correctly.

**Comment by JamesIves** [comment]
I believe `clean` is what you need in this case, here's a better explanation of this option than I could probably give: https://explainshell.com/explain?cmd=rsync+--delete (It just adds the `--delete` flag to the rsync command)

If you've deleted the files from your branch, but they exist on the remote, then the clean option will automatically delete them. This option is particularly useful for hashed files as it will prevent a build up of unused references. 

The exception to this rule is anything that is placed on the clean exclude list, along with `CNAME` and required `git` files.

**Comment by emma-sax4** [comment]
Ah ok that's what I thought, but I was scared to try it out until I was sure. I'll give that a shot!

**Comment by emma-sax4** [comment]
`clean` was the trick! Thank you! I was hoping that was the simple solution. ❤️  This action is wonderful.
