### ISSUE TITLE
Update NodeJS

### ISSUE THREAD

**Issue by bbenezech** [JamesIves/github-pages-deploy-action#305]
Node 10 is a bit old, it was first released at the beginning of 2018.

It broke my build when I tried to set the node engine in `package.json` to the minimum version accepted by latest Eslint (12.X)

Can we move to LTS Erbium 12.16.3 or newer?

**Comment by bbenezech** [comment]
Disregard, they only dropped support for 8.X, my bad.

**Comment by JamesIves** [comment]
Happy to look at any pull requests if you want to push it up, I don't see any reason to not update the Node version.
