### ISSUE TITLE
Check if source folder exists and exit with helpful error message

### ISSUE THREAD

**Issue by egil** [JamesIves/github-pages-deploy-action#310]
**Describe the solution you'd like**
Inspired by #308, where a previous step in a workflow didn't error out, even if the source folder was not create, a less helpful error message was returned by rsync. 

The action could help by checking if the source folder exists before calling rsync, and provide a helpful error message instead, if it doesn't.

**Comment by JamesIves** [comment]
Released with `3.5.4`: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.5.4

**Comment by JamesIves** [comment]
Sadly this was causing some issues so I've had to roll these changes back we can investigate further. For some reason the `fs.existsSync` command was throwing an error but I'm not really sure why.

This is the commit: https://github.com/JamesIves/github-pages-deploy-action/commit/5e3a0374ac43c200e850cfcffb5e16f80bcccf3d

I'm guessing the `existsSync` command is being executed incorrectly.

**Comment by JamesIves** [comment]
If anyone would like to pick this up for Hacktoberfest please take a look at my previous comment! I didn't have time to investigate why this is happening but it would be a great thing to add!

**Comment by JamesIves** [comment]
This has been added as part of [version 3.7.1](https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.7.1).
