### ISSUE TITLE
Add an option to run rsync with --checksum

### ISSUE THREAD

**Issue by LeszekSwirski** [JamesIves/github-pages-deploy-action#314]
It'd be nice to be able to run the `rsync` copy with `--checksum`, so that files that are newly generated but otherwise stay unmodified (in my case, doxygen output) aren't updated in the commit.

**Comment by JamesIves** [comment]
Thanks for the request - Can you think of any reason why this shouldn't be the default behavior?

**Comment by LeszekSwirski** [comment]
Hypothetically, I could imagine someone wanting to preserve modification times if e.g. they want to be able to `touch` files to trigger some post deploy `make` task. Also, I guess file checksumming could be more expensive for large files? Though git has to hash the files anyway so one already pays that cost.

Practically, I expect checksum to do what people want almost all the time, so I'd be fine with it being a default.

**Comment by JamesIves** [comment]
Works for me! I'll try and get this up this weekend.

**Comment by JamesIves** [comment]
Released with `3.5.4`: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.5.4
