### ISSUE TITLE
Permission to repo denied to github-actions[bot]

### ISSUE THREAD

**Issue by Eamonnzhang** [JamesIves/github-pages-deploy-action#330]
**Describe the bug**
i have add ACCESS_TOKEN in the Eamonnzhang/scratch-pc-preview repo

**Reproduce**
here is my yml config
`name: Build and Deploy To Scatch Pc Preview
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@master

    - name: Install and Build
      run: |
        npm install 
        npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.5
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        REPOSITORY_NAME: Eamonnzhang/scratch-pc-preview
`

**Logs**
![image](https://user-images.githubusercontent.com/9126544/84570985-21789500-adc3-11ea-8f65-acaef38310ca.png)

**Additional Comments**
the scratch-pc repo is private, but the scratch-pc-preview is public.

**Comment by Eamonnzhang** [comment]
I use SSH way finally and it works.

**Comment by kvark** [comment]
Can we re-open this? I'm also struggling to get that rolling with `ACCESS_TOKEN` right now. Switching to SSH is not a solution to this issue, it's a workaround. The documentation clearly states that `ACCESS_TOKEN` is required when using `REPOSITORY_NAME`.

**Comment by kvark** [comment]
Found a solution in https://github.com/JamesIves/github-pages-deploy-action/issues/243#issuecomment-611202870 🎉
