### ISSUE TITLE
Add error message if origin doesn't exist

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#335]
**Describe the bug**

If the action fails on `git rm origin` it's likely because the user hasn't run the `actions/checkout` step.  We should display a helpful error message if the action throws here.

**Comment by JamesIves** [comment]
There should be a clear error message now if origin doesn't exist. I'd like to move forward with an FAQ section that answers some of these problems so I'm going to keep this open for a little bit longer until that's done.

**Comment by JasonGross** [comment]
Why not just allow `git remote rm origin` to fail?  Is there a reason that users need to run the `checkout` action first?

**Comment by JamesIves** [comment]
It will error later in the process if it's allowed to fail. The `checkout` action is maintained by GitHub themselves and has a lot of configuration options which would make removing it as a dependency a hassle to maintain. In an ideal world an action could extend another without the need for it being included in the workflow file.

With that said I'm open to the idea of adding basic checkout functionality  if `actions/checkout` is not included in the workflow (We could run a few `git` commands similar to how the action checks if a branch exists on the remote or not). There's a pretty extensive [contribution guide](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md) if you'd like to take a crack at it.

**Comment by JasonGross** [comment]
Are you saying that the immediately following `git remote add origin ${action.repositoryPath}` will fail?  Or an even later step?

(https://github.com/JamesIves/github-pages-deploy-action/blob/578c32107671513e859b51172785a19a883b6bc8/src/constants.ts#L35-L36 claims that `repositoryPath` is autogenerated, but I can't find the code that generates it...)

Looking at the method used by https://github.com/actions/checkout to get the URL, at
https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/git-source-provider.ts#L20
https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/url-helper.ts#L11-L15
https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/input-helper.ts#L20-L35
https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/url-helper.ts#L22-L29

it looks like the code needed is (untested)
```ts
import * as core from '@actions/core'
import * as github from '@actions/github'
import {URL} from 'url'

# modified from https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/url-helper.ts#L5-L20 and https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/input-helper.ts#L20-L35
export function getFetchUrl(settings: IGitSourceSettings): string {
  const qualifiedRepository =
    core.getInput('repository') ||
    `${github.context.repo.owner}/${github.context.repo.repo}`
  core.debug(`qualified repository = '${qualifiedRepository}'`)
  const splitRepository = qualifiedRepository.split('/')
  if (
    splitRepository.length !== 2 ||
    !splitRepository[0] ||
    !splitRepository[1]
  ) {
    throw new Error(
      `Invalid repository '${qualifiedRepository}'. Expected format {owner}/{repo}.`
    )
  }
  const repositoryOwner = splitRepository[0]
  const repositoryName = splitRepository[1]

  const serviceUrl = getServerUrl()
  const encodedOwner = encodeURIComponent(repositoryOwner)
  const encodedName = encodeURIComponent(repositoryName)
  const sshKey = core.getInput('ssh-key')
  if (sshKey) {
    return `git@${serviceUrl.hostname}:${encodedOwner}/${encodedName}.git`
  }

  // "origin" is SCHEME://HOSTNAME[:PORT]
  return `${serviceUrl.origin}/${encodedOwner}/${encodedName}`
}


// from https://github.com/actions/checkout/blob/28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b/src/url-helper.ts#L22-L29
export function getServerUrl(): URL {
  // todo: remove GITHUB_URL after support for GHES Alpha is no longer needed
  return new URL(
    process.env['GITHUB_SERVER_URL'] ||
      process.env['GITHUB_URL'] ||
      'https://github.com'
  )
}
```

(I guess if you do this, though, it wouldn't pick up the credentials used from the checkout action, so it would be best to have this only as a fallback?)

I can try to prepare a PR with this, if you'd like?

**Comment by JamesIves** [comment]
The repository path gets generated here: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/lib.ts#L24 /  https://github.com/JamesIves/github-pages-deploy-action/blob/578c32107671513e859b51172785a19a883b6bc8/src/util.ts#L19

**Comment by JasonGross** [comment]
Ah, so you're already generating the remote URL.  I'm confused, then, where the action will fail if the origin remote did not previously exist.

**Comment by JamesIves** [comment]
I'll double check over the weekend - I can't remember the point of failure

**Comment by JamesIves** [comment]
I have a test branch that lets the origin step pass if it fails, (`releases/v3-origin`) however without running the checkout step prior it's not going to have access to the repository files so I don't really know how helpful this even is. There would need to be some rudimentary implementation of actions/checkout on top of this that downloads the repo into the workspace and sets up the required permissions for Git so the remainder of the workflow can continue.

**Comment by joshuanoronha** [comment]
Is the issue still open?

**Comment by JamesIves** [comment]
yep

**Comment by JamesIves** [comment]
Closing this as out of scope. Issue #429 fixes the issue where remote rm origin can fail which should hopefully be adequate.
