### ISSUE TITLE
Is there any way to make a cleanup of result folder?

### ISSUE THREAD

**Issue by Serg-Maximchuk** [JamesIves/github-pages-deploy-action#336]
**Is your feature request related to a problem? Please describe.**
Is there any way to make a cleanup of result folder? I see now lots of old build files in master branch

**Describe the solution you'd like**
would be nice to have some option `cleanup: true` or smth

**Additional Comments**

**Comment by Serg-Maximchuk** [comment]
Oh shoot, there is such a feature already

**Comment by JamesIves** [comment]
Glad you found it!
