### ISSUE TITLE
 '/usr/bin/git' failed with exit code 128 ❌

### ISSUE THREAD

**Issue by janothan** [JamesIves/github-pages-deploy-action#342]
**Describe the Issue**
What I want to do is very simple: My mvn process generates javadoc files that I want to publish via github pages.
The files are located in `/home/runner/work/jRDF2Vec/jRDF2Vec/target/site/apidocs`.
My personal access token is basic, I did not check any scopes.
Workflow Run: https://github.com/dwslab/jRDF2Vec/runs/803989000
Actions File: https://github.com/dwslab/jRDF2Vec/blob/master/.github/workflows/maven.yml

**Logs**

```
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
Running post deployment cleanup jobs… 🗑️
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

**Comment by JamesIves** [comment]
Change `GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}` to `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

The `GITHUB_TOKEN` arg is setup specifically for the built in GitHub token, not an access token. If you want to use an access token change the arg to `ACCESS_TOKEN`.

Let me know if that works.

**Comment by janothan** [comment]
Wow, great response time and a great answer! 🎉
Everything works now. Sorry, I was not aware that there is a `GITHUB_TOKEN` - I am quite new to GitHub actions.

The issue can be closed ✅

**Comment by JamesIves** [comment]
No problem! I'm glad it works.
