### ISSUE TITLE
Error messages are insufficiently informative

### ISSUE THREAD

**Issue by JasonGross** [JamesIves/github-pages-deploy-action#345]
**Describe the bug**
In https://github.com/coq-community/coq-performance-tests/runs/808286402?check_suite_focus=true, I see
```
Checking configuration and starting deployment… 🚦
Deploying using …… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
Running post deployment cleanup jobs… 🗑️
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
Deployment failed! ❌
```
This is not very useful.  Please also always display the error message reported by `git`

**Comment by JamesIves** [comment]
That is the error, the contextual message occurs right before this. By default the action runs in silent mode unless `ACTIONS_STEP_DEBUG` is turned on, but I'm not convinced that's the right approach right now as it silences helpful messages from Git and it requires some knowledge of how debugging in actions occurs. I may change this so the action always logs the commands being executed like it was before as it seems like a lot of people are getting confused by this. Perhaps I'll add an option that let's you turn it back to silent mode instead.

**Comment by JamesIves** [comment]
`3.5.6` is slated for release today which resolves this issue. If you'd like to silence the git commands you can now add `SILENT: true` to the config.
