### ISSUE TITLE
Action fails on Windows

### ISSUE THREAD

**Issue by JasonGross** [JamesIves/github-pages-deploy-action#348]
**Describe the bug**
```
##[error]The deploy step encountered an error: Unable to locate executable file: rsync. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file. ❌
```

**Logs**
https://github.com/JasonGross/reddit-watcher/runs/809819756?check_suite_focus=true

**Comment by JasonGross** [comment]
And even if I `choco install rsync`, I get `##[error]The deploy step encountered an error: The process 'C:\ProgramData\Chocolatey\bin\rsync.exe' failed with exit code 3762504530 ❌`, see https://github.com/JasonGross/reddit-watcher/runs/809832231?check_suite_focus=true

**Comment by JamesIves** [comment]
Please read: https://github.com/JamesIves/github-pages-deploy-action#operating-system-support-

Windows is not supported at this time.

**Comment by JamesIves** [comment]
This is [now being discussed as a potential improvement for version 4](https://github.com/JamesIves/github-pages-deploy-action/discussions/456).
