### ISSUE TITLE
The action does not deploy to the requested folder

### ISSUE THREAD

**Issue by OvidijusParsiunas** [JamesIves/github-pages-deploy-action#352]
**Describe the Issue**
I have used the sample config and have augmented it to deploy to BRANCH: master and FOLDER: dist. However, whilst it is deploying to the correct branch, it is not committing the build files to the correct directory and just placing it in root.
Please see my repository, where I expect the appBundle.js and browserSupportBundle.js to be committed to the dist folder, but they went to root instead.

The following is the config if that helps:

name: MyVision build
on:
  push:
    branches:
    - master
    - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.

**Logs**
  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f162090 changing readme logo and updating github actions
/usr/bin/git fetch ***github.com/OvidijusParsiunas/myvision.git
From https://github.com/OvidijusParsiunas/myvision
 * branch            HEAD       -> FETCH_HEAD
/usr/bin/git worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/master
Preparing worktree (detached HEAD f162090)
HEAD is now at f162090 changing readme logo and updating github actions
/usr/bin/rsync -q -av --checksum --progress dist/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
/usr/bin/git status --porcelain
?? appBundle.js
?? browserSupportBundle.js
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/u5nyt8un3
Switched to a new branch 'github-pages-deploy-action/u5nyt8un3'
/usr/bin/git commit -m Deploying to master from  @ f1620905c28a6e6660ce366ec98a92b7a83e4b92 🚀 --quiet
/usr/bin/git push --force ***github.com/OvidijusParsiunas/myvision.git github-pages-deploy-action/u5nyt8un3:master
To https://github.com/OvidijusParsiunas/myvision.git
   f162090..6c201ec  github-pages-deploy-action/u5nyt8un3 -> master
Changes committed to the master branch… 📦
/usr/bin/git checkout --progress --force f1620905c28a6e6660ce366ec98a92b7a83e4b92
HEAD is now at f162090 changing readme logo and updating github actions
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Completed deployment successfully! ✅

**Additional Comments**

**Comment by JamesIves** [comment]
If you want it to deploy to a specific folder you need to use the `TARGET_FOLDER` param.
