### ISSUE TITLE
[error]There was an error initializing the repository: Branch is required.

### ISSUE THREAD

**Issue by arothstein** [JamesIves/github-pages-deploy-action#355]
**Describe the Issue**

Stepping through the code, it appears that hasRequiredParameters tests the value of BRANCH using isNullorUndefined, which is evaluating true. However, the debug output shows that BRANCH has a value specified. Can't figure out what I am doing wrong.

**Logs**

https://github.com/arothstein/goodpassphrase/blob/master/.github/workflows/build.yml

##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'Deploy'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy
##[debug]Loading inputs
##[debug]Loading env
Run JamesIves/github-pages-deploy-action@3.5.7
  with:
  env:
    GITHUB_TOKEN: ***
    BASE_BRANCH: master
    BRANCH: gh-pages
    FOLDER: dist/spa

Checking configuration and starting deployment… 🚦
##[error]There was an error initializing the repository: Branch is required. ❌
Deployment failed! ❌
::set-env name=DEPLOYMENT_STATUS::failed
##[debug]DEPLOYMENT_STATUS='failed'
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy

**Additional Comments**

Thank you in advance for your help!

**Comment by JamesIves** [comment]
Swapping out `env:` with `with:` should fix this error.

**Comment by arothstein** [comment]
Thank you, that resolved the issue. I had originally been referencing https://github.com/analythium/github-pages-quasar which used env:, my bad for not doing a more diligent comparison.

**Comment by JamesIves** [comment]
No problem! The `master` branch is a much older version of this action before the `with` keyword existed.
