### ISSUE TITLE
Cleanup step fails to complete

### ISSUE THREAD

**Issue by stefanv** [JamesIves/github-pages-deploy-action#365]
In [our workflow](https://github.com/fritz-marshal/fritz/blob/master/.github/workflows/build-test-deploy.yaml) we are seeing the [following error](https://github.com/fritz-marshal/fritz/runs/872649531):

```
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
```

It seems like git should be able to remove the worktree, so I'm not sure why it is failing.

**Comment by JamesIves** [comment]
Does the action properly make the deployment? If not I'm guessing this isn't the actual error and it's failing higher up in the deployment.

My gut reaction is it's to do with your use of an ssh key and the `REPOSITORY_NAME` field. Did you add the deployment key to the repo you're attempting to deploy to?

**Comment by JamesIves** [comment]
```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```

There's also this. Looks like it's attempting to run a pre-commit hook that's throwing the error.

**Comment by thisismydesign** [comment]
I'm having a similar issue with `pre-commit`. Is there a way to add parameters to the `git commit`? Adding `--no-verify` would solve this for me.

```
/usr/bin/git commit -m Deploying to gh-pages from  @ 90a97b7dc96d435649acfd5474ebc135e04f742c 🚀 --quiet
/home/runner/work/dotdev/dotdev/.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
##[error]The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 1 ❌
Deployment failed! ❌
```

Overall I can't tell why this happens. It used to work, I tried with those versions but no luck. I'm getting this even with a clean installation after removing the cache. `pre-commit` version is the latest (and has been for 4 years).

**Comment by JamesIves** [comment]
I see no reason to not add the no-verify flag as the default option, this will make the deployment more predictable. I'm happy to add this either later today or early tomorrow.

**Comment by thisismydesign** [comment]
Thanks! If you don't want it to change existing functionality, the ability to extend the command with custom parameters would also be an option.

**Comment by JamesIves** [comment]
I can't think of a situation where a pre-commit hook would/should be used in conjunction with the commands it performs, but maybe I'm missing something?

**Comment by thisismydesign** [comment]
Me neither really. :)

**Comment by stefanv** [comment]
That would probably solve our problem too, thanks!

**Comment by JamesIves** [comment]
Released as part of this update: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.5.9

**Comment by thisismydesign** [comment]
Thanks a lot for the quick fix!

**Comment by stefanv** [comment]
Thanks very much, indeed!

**Comment by SooluThomas** [comment]
I'm still facing this error (even after bumping to the latest version). This is weird because it is working fine on a few jobs and errors randomly. ([link](https://github.com/qiskit-community/qiskit-translations/runs/923742507?check_suite_focus=true#step:9:27))

<img width="825" alt="image" src="https://user-images.githubusercontent.com/11485594/88831711-b978e500-d19d-11ea-9c32-8f26d5c2f5c0.png">

Is there a way to fix this? Thank you.

**Comment by stefanv** [comment]
Could we catch the git error and print it out, to make debugging easier?

**Comment by JamesIves** [comment]
It gets printed right before the generic git error;

@SooluThomas Can you turn disable `SILENT` and re-run the job? It's also recommended that you lock the version to the latest release as it's possible GitHub Actions is running a cached version: `JamesIves/github-pages-deploy-action@3.5.9`

**Comment by SooluThomas** [comment]
Yes, it worked. Thank you!!

**Comment by SooluThomas** [comment]
@JamesIves it's failing again :(

**Comment by JamesIves** [comment]
Can you link me to the workflow failures so I can debug?

**Comment by SooluThomas** [comment]
Sure, https://github.com/qiskit-community/qiskit-translations/runs/930487388?check_suite_focus=true#step:9:167
