### ISSUE TITLE
Use `with` instead of `env`

### ISSUE THREAD

**Issue by mitinarseny** [JamesIves/github-pages-deploy-action#37]
Better to use [jobs.<job_id>.steps.with](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswith) instead of env variables as it more stable and GitHub Actions is responsible for handling missing args, not your [`entrypoint.sh`](https://github.com/JamesIves/github-pages-deploy-action/blob/master/entrypoint.sh).

**Comment by JamesIves** [comment]
I like the idea of this. I'm currently working on version 2 of this action so I'll probably push it in as part of that.

**Comment by mitinarseny** [comment]
By the way, do you consider to move installation of dependencies (`apt-get update && apt-get install -y git jq`) to dockerfile and push your image with it on Docker Hub? It would save time on Github Actions to pass your action.

**Comment by JamesIves** [comment]
Currently the idea is to deprecate the Docker version of this action in favor of the Actions Toolkit. This will remove the requirement for these.

**Comment by JamesIves** [comment]
Planned: https://github.com/JamesIves/github-pages-deploy-action/issues/39

**Comment by JamesIves** [comment]
Available in the v3 beta. Please give it a try and let me know if you encounter any problems.

`JamesIves/github-pages-deploy-action@releases/v3-beta`.
