### ISSUE TITLE
Deploy to gh-pages branch with LFS disabled

### ISSUE THREAD

**Issue by riga** [JamesIves/github-pages-deploy-action#373]
Hi!

First of all, great action 🎉

**Is your feature request related to a problem?**

Image files in the branch of my repository that I'd like to deploy to GitHub pages are versioned via Git LFS. However, GitHub pages itself does not support serving LFS-maintained content from a (`gh-pages`) branch. It would be awesome to have an option in your deploy action that would cause all LFS-maintained files to be removed from LFS, added the "normal" git-way to the repository, and then deployed to the `gh-pages` branch.

**Describe the solution you'd like**

I think optionally adding `git lfs migrate export --include="*"` would do the trick.

Do you think that's possible or am I perhaps missing something?

**Comment by JamesIves** [comment]
Do you think it would make more sense to have this option be disabled by default, and instead remove this command from being run using `LFS: false` or something similar?

**Comment by riga** [comment]
Yes, having a flag to toggle this behavior sounds good to me. I don't have a strong opinion in the default value though :)

**Comment by JamesIves** [comment]
This has been added in `3.6.0` and can be toggled on using `LFS: true`. If you find any issues with this please feel free to open a new ticket so it can be appropriately tracked: https://github.com/JamesIves/github-pages-deploy-action/releases

**Comment by riga** [comment]
Thanks @JamesIves ! 🎉🎊

**Comment by Pike** [comment]
@riga , can you share where you're using LFS and this action? I started wondering where the LFS-ness shows up, if it's in the checkout or in the publishing workspace, and if my understanding of the `.gitattributes` role is right.

Thanks.

**Comment by riga** [comment]
@Pike In my main branch, I have files stored in LFS and one needs to prevent that those files are still LFS references in the `gh-pages` branch because GitHub will only checkout these references. To overcome this, the feature James implemented takes these files out of LFS and adds them as normal files to the `gh-pages` branch.

**Comment by Pike** [comment]
So the way I understand the code, the following happens

* update to the base branch in the workflow dir
* migrate lfs files into regular files (should modify `.gitattributes` and git history, per docs)
* rsync the folder to the gh-pages worktree
* commit and push in the gh-pages worktree

Now, the use of `lfs migrate export` sounds pretty intense in its side-effects, but I'm also not sure it does anything. When running the command in my local clone of https://github.com/Apress/repo-with-large-file-storage, it doesn't seem to actually change the current state.

I understand the intent, but I'd expect some sort of `git lfs untrack` being run in the gh-pages worktree to do that.

All that said: in theory, there's no difference between theory and practice, but in practice there is. Thus, if you can share which repo and workflow you're using this option in in practice, I'd love to take a look at that.

**Comment by riga** [comment]
I am actually still using the `git lfs migrate export --include="*"` command I suggested at the top in [this project](https://github.com/cms-ml/documentation/blob/master/.github/workflows/deploy_docs.yml#L41) as I had no time to update it yet to the new version of this action.

Images like [this one](https://github.com/cms-ml/documentation/blob/master/content/images/favicon.png) in the master are still in LFS, while the deployed [gh-pages version](https://github.com/cms-ml/documentation/blob/gh-pages/images/favicon.png) is not.

**Comment by Pike** [comment]
Thanks for the pointer. I filed a PR to change the approach of handling lfs, I think for the better.

As far as the action here is concerned, the migrate export won't do the trick, as it only modifies local commits. I'll open a new issue.
