### ISSUE TITLE
rsync not setting directory correctly

### ISSUE THREAD

**Issue by antoniogamiz** [JamesIves/github-pages-deploy-action#378]
**Describe the bug**

I am trying to deploy to gh-pages using a directory. `rsync` tries to use this directory:

`rsync: change_dir "/__w/Documentable/Documentable//html" failed: No such file or directory (2)`

**Reproduce**

[workflow](https://github.com/Raku/Documentable/blob/develop/.github/workflows/integration-run.yml).

**Logs**

 [output](https://github.com/Raku/Documentable/runs/914257294?check_suite_focus=true).
[output with debug set to true](https://github.com/Raku/Documentable/actions/runs/185518509)

**Comment by JamesIves** [comment]
Before the deployment step runs can you add a `ls` to see if the `html` directory actually exists in the workflow? I don't _think_ the double slash should cause an issue here but I could be mistaken.

**Comment by JamesIves** [comment]
Closing this as I didn't get a response - please feel free to comment if you still need help.
