### ISSUE TITLE
need help deploying to gh-pages

### ISSUE THREAD

**Issue by shahzebsiddiqui** [JamesIves/github-pages-deploy-action#381]
Hello,

I have a [github action](https://github.com/buildtesters/schemas/blob/master/.github/workflows/jsonschemadocs.yml) that i was hoping you can help with. I am build json schema into README docs using [jsonschema2md](https://github.com/adobe/jsonschema2md) and it is working, but I am unable to deploy pages. The jsonschema2md will publish markdown content as part of CI and then these are pushed to gh-pages. I was really hoping you can help me troubleshoot what is the issue. I have a sample build https://github.com/buildtesters/schemas/runs/928309105?check_suite_focus=true and error fails in rsync

```
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
##[error]The deploy step encountered an error: The process '/usr/bin/rsync' failed with exit code 23 ❌
```

**Comment by JamesIves** [comment]
Can you please post a sample of your workflow yml file?

**Comment by shahzebsiddiqui** [comment]
My file is here https://github.com/buildtesters/schemas/blob/master/.github/workflows/jsonschemadocs.yml

The setup is quite complex at time when i posted issue i saw an rsync issue so i figured job was not seeing artifacts between job steps so i tried to stage job artifacts across jobs using https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts now i was able to upload my artifact but had issue with pushing. If i get this done right i think the pages should go in `gh-pages` whenever their is a `push` to `master` branch.

**Comment by shahzebsiddiqui** [comment]
here is my latest build see https://github.com/buildtesters/schemas/pull/76/checks?check_run_id=942438412 i have tried using github token to deploy pages now i am getting error 

```
Run JamesIves/github-pages-deploy-action@3.5.9

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ FAQ/Wiki: https://github.com/JamesIves/github-pages-deploy-action/wiki
    🔧 Support: https://github.com/JamesIves/github-pages-deploy-action/issues
    ⭐ Contribute: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/CONTRIBUTING.md

    📣 Maintained by James Ives (https://jamesiv.es)
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
/usr/bin/git init
Initialized empty Git repository in /home/runner/work/schemas/schemas/.git/
/usr/bin/git config user.name shahzebsiddiqui
/usr/bin/git config user.email shahzebsiddiqui@users.noreply.github.com
/usr/bin/git remote rm origin
fatal: No such remote: 'origin'
##[error]There was an error initializing the repository: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

**Comment by shahzebsiddiqui** [comment]
Okay so i have been able to work around the SSH key issue and now trying to add `BASE_BRANCH` in my case is `master` and pushing to `gh-pages`. I am still running into weird issue with remote origin. See this build https://github.com/buildtesters/schemas/runs/942528531?check_suite_focus=true

I have a PR https://github.com/buildtesters/schemas/pulls i am testing this and having trouble your help would be appreciated.

**Comment by JamesIves** [comment]
You're missing the `checkout` step that is mentioned in the README, it needs to come before the deploy step as it sets up the necessary Git tasks for this action to work correctly. There's an issue open that looks into potentially circumventing this requirement but it's not implemented yet. #331

**Comment by shahzebsiddiqui** [comment]
Okay i made some progress but now i get `rsync` error see https://github.com/buildtesters/schemas/runs/943030266?check_suite_focus=true

It says `docs` is not found so i created a docs directory in gh-pages https://github.com/buildtesters/schemas/tree/gh-pages just to circumvent this issue but still getting error. I am still working on this PR https://github.com/buildtesters/schemas/pull/76 to get this working still no luck. 

I am tempted to do an initial push from the downloaded artifact to get the docs published but ideally i want this automated. The idea behind this workflow is automate schema documentation whenever schema changes in `master` branch to do a push into `gh-pages` branch which will host the schema docs in https://buildtesters.github.io/schemas/ Right now i am using the `master` branch to host github pages but once this workflow is running i will switch to `gh-pages`. In any case this last step is critical to getting this pipeline running.

**Comment by shahzebsiddiqui** [comment]
Hi @JamesIves, 

I am having trouble getting this pipeline running, would you mind taking a look at my PR https://github.com/buildtesters/schemas/pull/76 its failing in `Deploy` stage. I have setup a key and using `checkout` step as you mentioned. I was able to get ssh working now its just matter of getting rsync working.

see build https://github.com/buildtesters/schemas/runs/964220732?check_suite_focus=true

I see an extra / in line ``rsync: change_dir "/home/runner/work/schemas/schemas//docs" failed: No such file or directory (2)`` which i dont understand how thats happening.  I have pushed a copy of generated docs to `gh-pages` with a manual push https://github.com/buildtesters/schemas/tree/gh-pages/docs  so there is a directory `docs` that should get updated as schema changes.

**Comment by JamesIves** [comment]
It looks like you're uploading/downloading an artifact called `schemadocs`, you need to match the folder name to the artifact name in your build.

In your deployment configuration try changing `FOLDER: docs` to `FOLDER: schemadocs`

**Comment by shahzebsiddiqui** [comment]
Thanks @JamesIves so i was able to get the pipeline running https://github.com/buildtesters/schemas/runs/967757903 had to troubleshoot the path i added an extra step and downloaded the artifact to ``downloads/docs``. What's not clear to me is the `FOLDER` field. I dont see any push to my `gh-pages` branch https://github.com/buildtesters/schemas/tree/gh-pages. The workflow is running but it not pushing the content to the other branch, its as if there were no files to commit.

What i'd like to do is have my workflow run on push to `master` branch which builds the schema docs and push them to `gh-pages`. Once this is automated i can switch my repo gh-pages branch so that https://buildtesters.github.io/schemas/ will show the content of the schemas.

A few things that are not clear, if there is no diff in my schema docs will the Deploy Pages workflow push with another commit. I'd only want to trigger this workflow if there is change to any schema file.

**Comment by JamesIves** [comment]
If you want the contents of `docs` deployed then you need to make the `FOLDER` field match `downloads/docs` not `downloads`, otherwise you're instructing the action to deploy the entire contents of `downloads` which is why you're seeing a folder at the root level in the branch. 

If there's no diff between the proposed changes and what's in the deployment branch then the action will exit without committing the changes, this is why you'll sometimes see `There is nothing to commit. Exiting early… 📭`

**Comment by shahzebsiddiqui** [comment]
I got it now, i was able to push with this workflow build https://github.com/buildtesters/schemas/runs/971799958?check_suite_focus=true into `gh-pages` https://github.com/buildtesters/schemas/tree/gh-pages with my commit https://github.com/buildtesters/schemas/pull/78 this looks good. i think this can work, it was a bit complicated workflow. I guess i will want to add my own docs apart from schemasdocs in `gh-pages` so perhaps i should have DeployPages use TARGET_FOLDER to specify where to push the docs. Right now it just spat them out in top-level folder. 

I won't want this workflow overwrite changes other than schemadocs, let's see how this goes. In the meantime i appreciate your help we can close this issue.
