### ISSUE TITLE
rsync failing with "permission denied" when deploying to GitHub pages

### ISSUE THREAD

**Issue by mluisbrown** [JamesIves/github-pages-deploy-action#388]
**Describe the Issue**
In the deploy step of my workflow, rsync fails with "permission denied" which then leads the deploy to fail with `##[error]The deploy step encountered an error: The process '/usr/bin/rsync' failed with exit code 23 ❌`

I copied the workflow from [this repo](https://github.com/pointfreeco/swift-composable-architecture) of which mine is an independent fork. In the original repo the same yaml file seems to work fine.

I tried using `ACCESS_TOKEN` first (as in the original, after having setup an access token secret), and had the same issue. I'm now trying using `GITHUB_TOKEN` but the issue remains. 

**Logs**
Here is a link to a failing log: https://github.com/trading-point/reactiveswift-composable-architecture/runs/946604768?check_suite_focus=true#step:5:97

Here is my workflow yaml file: https://github.com/trading-point/reactiveswift-composable-architecture/blob/michael/documentation/.github/workflows/documentation.yml

**Comment by JamesIves** [comment]
Interesting, I've never seen this error before. Have you tried using `chmod` on the directory/files to apply read+write permissions?

**Comment by mluisbrown** [comment]
I'm not sure how I would run `chmod` on the directory/files in the middle of the workflow. Also, I noticed that in the original repo when the Documentation workflow is run there is an `Update permissions` step which does `sudo chown --recursive $USER Documentation` (see [here](https://github.com/pointfreeco/swift-composable-architecture/runs/923865760?check_suite_focus=true#step:5:1). But I can't for the life of me see where this step is coming from 😕

**Comment by mluisbrown** [comment]
Ok, I found it. In the version for which the workflow was run, it still had the `Update Permissions` step, which I've added to my own workflow to test out.

**Comment by mluisbrown** [comment]
Ok, adding the `chown` step fixes the problem. Looks like it's related to this: https://github.com/SwiftDocOrg/swift-doc/pull/146 which despite what it says, is still not fixed. The issue is not related to this repo though so I'm closing the issue.
