### ISSUE TITLE
Version 3.0.0

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#39]
## `Version 3.0.0`
I'm currently working on the next iteration of this action, here are the proposed changes.

* The action will be re-written using the Action Toolkit API using TypeScript. The reason for this change is simply due to better testing, and because GitHub actions seem to be going more in this direction.
* The action will no longer build projects. With the changes to the actions API it's much easier to simply add a build step before the action runs. It's a bit pointless to have a supported step in the process that is specifically for Node based projects. As it's more agnostic the idea is that it can now support any form of framework/env.
* The action will utilize `with` instead of `env` and will now error straight off the bat if there's something missing.

### Progress
I'm hoping to have most of this work wrapped up this week.

- [X] Re-write core functionality using the action using the actions/toolkit API.
- [x] Make it so the action uses the `with` case in the workflow file.
- [x] Add a `.nojekyll` flag.
- [x] Write the branch creation functionality using the actions/toolkit API.
- [x] Write unit tests.
- [x] Automate the deployment. 
- [x] Create a `releases/v2` branch so legacy versions can continue to work.
- [x] Add dev tooling so the code remains consistent.
- [x] Verify that the action works correctly with the proposed changes.

**Comment by JamesIves** [comment]
Running into a few delays with this version release. I'm still working on it though.

**Comment by JacksonMaxfield** [comment]
Just wanted to say thanks for both the original project and release and for planning to make this action multi-language supported. :+1:

**Comment by JamesIves** [comment]
Version 3 is now released, please refer to the release notes for migration steps and details. Thanks for your patience everyone! 

https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.0.0
