### ISSUE TITLE
Allow pushing/deploying to protected branches

### ISSUE THREAD

**Issue by BryceMehring** [JamesIves/github-pages-deploy-action#41]
**Describe the bug**

If the deploy branch is protected, the deploy fails with the following error: `remote: error: Cannot force-push to a protected branch `.

Can we allow pushing to protected branches?

**Comment by JamesIves** [comment]
I don't think this is possible as protected branches have specific rules that need to be followed before pushing is allowed. If the deployment step is automatically pushing to the branch does it need to be protected to begin with?

**Comment by BryceMehring** [comment]
I've enabled branch protection only to prevent force pushing which this
project utilizes. There are other forms of branch protection which I'm not
using which I agree is overkill for an automated deployment.
