### ISSUE TITLE
Upgrade eslint-plugin-github to version 4

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#419]
This dependency has been failing for some time. The ideal solution for this would be:

* Update the dependency on a branch.
* Fix the linting errors it's complaining about.

_Originally posted by @JamesIves in https://github.com/JamesIves/github-pages-deploy-action/pull/371#issuecomment-691559490_

**Comment by pheeel** [comment]
Hi! Please, take a look at my PR
https://github.com/JamesIves/github-pages-deploy-action/pull/437

**Comment by JamesIves** [comment]
Resolved and merged, thank you so much!
