### ISSUE TITLE
multiple commits to gh-pages

### ISSUE THREAD

**Issue by shahzebsiddiqui** [JamesIves/github-pages-deploy-action#433]
I would like to know if its possible to have a single commit as pose to multiple commits from a workflow. See my commit history https://github.com/buildtesters/buildtest/commits/gh-pages 

The workflow is here https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/jsonschemadocs.yml basically i have three different jobs that publish content of schema files, schema docs, and examples in separate location. Since each job uses the github page action it causes a separate commit per job so i have 3 commits on gh-pages for every single merge to develop. Is there a way around this?

I though about having one job but i wasn't sure how to get my contents in right place.
The top-level folders `docs`, `schemas` and `examples` in gh-pages branch should exist.

**Comment by JamesIves** [comment]
Take a look at the SINGLE_COMMIT option, I believe that may be what you're looking for.

**Comment by shahzebsiddiqui** [comment]
So SINGLE_COMMIT won't work since I will lose my changes since I make commits to documentation pages as well. I would think there should be way to bundle multiple FOLDER items into different TARGET_FOLDER. Maybe a dict mapping on where files need to be copied would be more efficient. If that could be done I can bundle my three jobs into one job

**Comment by JamesIves** [comment]
This seems like a good use case for a way to add a root directory as the target folder, that way you could do something like this:

```
         FOLDER: downloads
         TARGET_FOLDER: .
```

This option exists for FOLDER but not TARGET_FOLDER. I'm going to link this issue with #387 as I think this would likely also be by implementing absolute paths.

**Comment by shahzebsiddiqui** [comment]
so it turns out this approach removes my documentation top-level README.md see https://github.com/buildtesters/buildtest/tree/gh-pages this commit https://github.com/buildtesters/buildtest/commit/b31e2dfa9181fc18c9f5c6f54daab1a94e2e6686 fix the issue of multiple commits but if you notice in previous commit my files https://github.com/buildtesters/buildtest/tree/524d8a55fc30ff88b656292794b72d42a510fdc0 there is a README and `_config.yml` that got erased. I think `TARGET_FOLDER: autogen-pages` or something like that where we keep auto-generated pages may be good to separate docs. I would think `TARGET_FOLDER` should not erase all files during sync if they specify a path such as root of repo.

**Comment by JamesIves** [comment]
Please take a look at the PRESERVE option that was added with 3.6.2, it may be what you're looking for.

**Comment by shahzebsiddiqui** [comment]
Thanks @JamesIves this may come in handy, right now i have directed my autogenerated pages in a separate page i will try out this option and bump the version thanks for your help. You can close this issue.
