### ISSUE TITLE
Update Node from 10 to 12

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#441]
**Describe the bug**

Right now the `.nvmrc` file points to Node 10. This is two versions out of date and should be updated to use the latest Node version. 

**Additional Comments**

* Change the node version, install with `nvm use`.
* Run the usual commands, `yarn install, yarn format, yarn lint, yarn test`. Ensure there are no issues.
* Make applicable readme and fixes to ensure it's clear to the user that this action runs on Node 12+.

This task also needs to be performed in another project related to this one: https://github.com/JamesIves/fetch-api-data-action/issues/186

* This would be a great task for someone looking to get contributions for Hacktoberfest!

**Comment by subhashissuara** [comment]
@JamesIves Can I work on this?

**Comment by JamesIves** [comment]
Go for it! I've assigned the issue to you.

**Comment by subhashissuara** [comment]
Thank you! I did the setup and ran the commands as instructed and there weren't any errors. I am attaching the screenshots for your reference:
![image](https://user-images.githubusercontent.com/28859415/94930263-c7bbe800-04e3-11eb-9ea5-f23624ca4da3.png)
![image](https://user-images.githubusercontent.com/28859415/94930340-e15d2f80-04e3-11eb-96e5-35f10c34c455.png)
![image](https://user-images.githubusercontent.com/28859415/94930375-ee7a1e80-04e3-11eb-9b78-2a4593dee91a.png)
![image](https://user-images.githubusercontent.com/28859415/94930430-0356b200-04e4-11eb-983f-b963abbcce63.png)
![image](https://user-images.githubusercontent.com/28859415/94930473-12d5fb00-04e4-11eb-8d23-e7d73ac37c5b.png)


> Make applicable readme and fixes to ensure it's clear to the user that this action runs on Node 12+.

Can you describe/refer to how I can ensure this?

**Comment by JamesIves** [comment]
Looks good to me, if those are passing than the inner workings of the actions behave as expected. I'd say all that's left is making a PR with the updated node version in the `nvmrc` file.

**Comment by subhashissuara** [comment]
> Make applicable readme and fixes to ensure it's clear to the user that this action runs on Node 12+.

@JamesIves  I need not work on this? If yes, can you describe what should do exactly?

**Comment by JamesIves** [comment]
Yeah taking another look I don't know how necessary it is to mention this as we already point to the use of the nvmrc file.

**Comment by subhashissuara** [comment]
Yes, that does make sense. Thank you!
