### ISSUE TITLE
Add option to redirect from the main page url to a subfolder (.htaccess / ...)

### ISSUE THREAD

**Issue by marcauberer** [JamesIves/github-pages-deploy-action#452]
Hi,
first of all, thanks for your awesome action!
Problem: If I click on the link of my GH page in the environments section of my repo, I get an 404 error, because there is no index.html or something in the root dir. What I want is to achieve a redirect to a subfolder, where the index.html lives. I know: I could add a small script for redirecting manually before calling your action, but I think this would be a great feature for you!
I don't know on which webserver architecture GitHub is based. If it was Apache, we could simply generate a .htaccess file with redirection rules. Another quick (but in my eyes dirty) solution would it be to generate a small index.php file ...

Would appreciate a realization, thanks in advance,
Marc

**Comment by JamesIves** [comment]
Thanks for the issue,

Unfortunately this is out of scope for this project. GitHub Pages does not support PHP nor does it support the use of a `.htaccess` file at this time. However even if it did the expectation would be for the user to commit that to their repository so the action could deploy the files into the branch.
