### ISSUE TITLE
Possible deprecation of the readme example using SSH

### ISSUE THREAD

**Issue by tlienart** [JamesIves/github-pages-deploy-action#454]
Hello, in the README part describing 'using an SSH Deploy Key', the example uses `ssh-agent@v0.2.0`. 

I was using this as well but it seems it's now broken because of https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ which they've fixed in a recent release `ssh-agent@v0.4.1`. 

It's not just a mere case of updating the version though, the key generation format needs to be upgraded as well, as far as I understand it needs to be in PEM format. And so should be something like

```
ssh-keygen -m pem [other options]
```

I would PR for this but I'm not entirely comfortable with the way GitHub actions work and so it might be good to have someone validate that the suggested changes above (use 0.4.1 + use a PEM key) is enough to get things to 'just work'.

**Comment by JamesIves** [comment]
Ah yes I noticed this the other day when running one of my own workflows. I've been thinking about this for some time and I'm wondering if adding native SSH key support to this repository would be a good idea or not. It does seem like a slight disconnect where a GitHub token and a PAT can be natively added via the secrets menu, but the SSH key relies on setting a boolean and using a third party action.

**Comment by tlienart** [comment]
> Ah yes I noticed this the other day when running one of my own workflows. I've been thinking about this for some time and I'm wondering if adding native SSH key support to this repository would be a good idea or not.

This would be really great as there would only be a single action (apart from checkout but that looks pretty stable) to monitor.

**Comment by JamesIves** [comment]
I am thinking of also removing the usage of actions/checkout too. If you have any thoughts please share them here: https://github.com/JamesIves/github-pages-deploy-action/issues/455

In the meantime I've prepared a doc adjustment for for the SSH changes. It will be bought in-house in `4.0.0` when that lands.

**Comment by JamesIves** [comment]
README updated, moving discussion for future improvements to #459 

Thanks for the report!
