### ISSUE TITLE
GitHub Pages build failed

### ISSUE THREAD

**Issue by freearhey** [JamesIves/github-pages-deploy-action#48]
**What's the problem?**

Every time an action is triggered, I get the "Your site is having problems building: Page build failed." error.

**I tried to replace `GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}` with `ACCESS_TOKEN: ${{ secret.REPO_SCOPED_TOKEN }}`.**

Didn't help.

**I tried to add a `.nojekyll` file to the build.**

Didn't help.

**I tried using `JamesIves/github-pages-deploy-action@releases/v3`.**

Didn't help.

**I tried to add a `.nojekyll` file directly to `gh-pages` branch.**

But,

>  You can safely commit these files directly into deployment branch without them being overridden after each deployment

is definitely not true. All files are erased every time.

**Expected behavior**

No errors will occur after deployment.

Therefore, I would appreciate any help in solving this problem.

**Comment by freearhey** [comment]
And yes, I forgot to mention that if I manually add the `.nojekyll` file to the `gh-pages` branch after deployment, then the error disappears.

**Comment by JamesIves** [comment]
I've noticed this too and I've been holding back on releasing the new version because of it. I've emailed GitHub support about it with a very vague response from them. It seems like something has changed this last week, because previously the error was only caused if you are using a GitHub token, but they told me it's because a human didn't trigger the build even though an access token with a very greedy permission scope was used.

```
Oh interesting - we'll dig into this more and followup if we have more questions.
```

@tcbyrd - If you're available are you able to look into this? I have a test repo with the issue: https://github.com/JamesIves/doughnut-generator

**Comment by JamesIves** [comment]
Also @freearhey some of the issues you're referring to such as the `CNAME` and `.nojekyll` items are only relevant to `v3`, which hasn't been released yet. If you're using `v2` you need to follow the steps in that README.

**Comment by freearhey** [comment]
@JamesIves I brought the text from the docs of `v3` precisely because I tried to use `v3` in this case. At that time, I thought that the problem could be precisely that `.nojekyll` is recreated every time from scratch. When using `v2`, of course I was guided by the documentation for `v2`.

**Comment by JamesIves** [comment]
> @JamesIves I brought the text from the docs of `v3` precisely because I tried to use `v3` in this case. At that time, I thought that the problem could be precisely that `.nojekyll` is recreated every time from scratch. When using `v2`, of course I was guided by the documentation for `v2`.

Please follow the instructions here to try the beta of v3 - https://github.com/JamesIves/github-pages-deploy-action/tree/releases/v3-beta

If you're still experiencing the issue you mentioned with the CNAME files please open a new issue. I'd like to keep this on-topic for the deployment issue.

**Comment by Fndroid** [comment]
Same issue. All actions run passed but Github page deploy failed.
![image](https://user-images.githubusercontent.com/16091562/69003320-7e4dc300-093a-11ea-8a07-ff7d1f60258e.png)

**Comment by linbudu599** [comment]
I also got depressed by this problem..., I found something special, the first time you run the action in v2/v3, the page will be built successfully, but if u update sth and push, when the action goes there will be one more workflow 'github pages', although it shows success the page still failed in building.
![image](https://user-images.githubusercontent.com/48507806/69139963-8e150500-0afc-11ea-934b-c91779ba86fc.png)

**Comment by shilangyu** [comment]
This seems to be a problem for all gh-pages deploy actions. Switching to master branch in settings/Github_Pages and then switching back to gh-pages cause it to deploy correctly

**Comment by JamesIves** [comment]
Just got word back from GitHub support. Essentially what's happening here is that the `GITHUB_TOKEN` is being persisted by another action, causing the failure when it gets to the deploy step.

Update the `actions/checkout` step in your config to point to `v1` and this issue should be resolved.

```
    steps:
    - name: Checkout
      uses: actions/checkout@v1
```

Just tested it and it worked for me. With that being said I'm going to push up `v3` today.

**Comment by shilangyu** [comment]
I used v2 and releases/v3 of `github-pages-deploy-action` with checkout@v1 to no avail. Getting the same error `'GitHub Pages build failed'`. [Heres](https://github.com/shilangyu/actions-testing/blob/master/.github/workflows/ci.yml) an example project. Its hosted on [shilangyu.dev/actions-testing](https://shilangyu.dev/actions-testing) and you can see the content does not match the gh-pages branch.

**Comment by JamesIves** [comment]
> I used v2 and releases/v3 of `github-pages-deploy-action` with checkout@v1 to no avail. Getting the same error `'GitHub Pages build failed'`. [Heres](https://github.com/shilangyu/actions-testing/blob/master/.github/workflows/ci.yml) an example project. Its hosted on [shilangyu.dev/actions-testing](https://shilangyu.dev/actions-testing) and you can see the content does not match the gh-pages branch.

Try changing `GITHUB_TOKEN` out for a personal access token in the deploy step and it should work.

**Comment by freearhey** [comment]
Changing the `actions/checkout` version to `v1` really helped. I also had to roll back to `JamesIves/github-pages-deploy-action@master` because `v3` currently causes a `'Cannot read property 'name' of undefined'` error. But the main problem is solved, so thank you anyway!

**Comment by JamesIves** [comment]
@freearhey Can you open an issue with the v3 issue with the logs?

**Comment by shilangyu** [comment]
> Try changing `GITHUB_TOKEN` out for a personal access token in the deploy step and it should work.
This does work. Let's hope `GITHUB_TOKEN` gets a fix soon

**Comment by JamesIves** [comment]
From what I understand it's in the works on GitHubs end, but not ready yet. This action just supports it for when it does work. I pre-maturely added it because people kept trying it anyway,.

**Comment by ghost** [comment]
@JamesIves I'm getting this issue, switching to v1 didn't help. I'm already setting `with: token` with a PAT. I'm using Github Enterprise. Any clue?

**Comment by JamesIves** [comment]
> @JamesIves I'm getting this issue, switching to v1 didn't help. I'm already setting `with: token` with a PAT. I'm using Github Enterprise. Any clue?

This is a very old issue. Please create a new issue or discussion that outlines your problem and I'll do my best to support.

**Comment by pavelkornev** [comment]
@JamesIves I'm facing the same issue as @leoglobant... using GitHub Enterprise, once deployed by this GH Action — build fails, if I deploy the same files manually — everything works.

I do have
```
permissions:
  contents: write
```

in the workflow file and using `checkout@v2` and `github-pages-deploy-action@v4`

And I see that files are deployed/committed properly to `gh-pages` branch. I don't understand what is the root cause of such GitHub behaviour. Any suggestions?

**Comment by pavelkornev** [comment]
Switching to use Token instead of permissions in the workflow file helped me to solve the issue (maybe update documentation?).

**Comment by vishalsinghkyndryl** [comment]
Hi @pavelkornev , could you please share the source code for the workflow file. Facing this same issue

**Comment by dayo09** [comment]
> Switching to use Token instead of permissions in the workflow file helped me to solve the issue (maybe update documentation?).

This issue helped me a lot :-D Thanks.

To be specific, I registered a PAT of maintainer account and passed it as `github-pages-deploy-action`'s token, and it works now.

In my case, I hadn't set `with: token:` at all, but my workflow worked well. It's because the action's always triggered by maintainers, so it was given the default GITHUB_TOKEN enough to push to `gh-pages`. 
However, for some reason, it seems not to have enough permission to deploy github pages.
So I set PAT of maintainer account as `github-pages-deploy-action`'s token and all is fine now.

Reference:

https://docs.github.com/en/enterprise-server@3.5/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-from-a-branch


> Who can use this feature
> 
> People with admin or maintainer permissions for a repository can configure a publishing source for a GitHub Pages site.

> Note: If your site has not published automatically, make sure someone with admin permissions and a verified email address has pushed to the publishing source.

**Comment by james-s-w-clark** [comment]
For me, on Checkout v1 / v3 in GitHub Enterprise, setting write permissions [as the readme suggested](https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane) didn't help - still get `Your site is having problems building: Page build failed`. 

Switching GH Pages to `main` and back to `gh-pages` fixes the error, and the website looks good (temporary manual solution, to prove the files are correct).

I will try the token suggestion above.
