### ISSUE TITLE
Use `GITHUB_TOKEN` instead of `ACCESS_TOKEN`

### ISSUE THREAD

**Issue by gerardabello** [JamesIves/github-pages-deploy-action#5]
**Describe the solution you'd like**

The action should use `GITHUB_TOKEN` instead of a user-provided `ACCESS_TOKEN`

**Additional Comments**

It's much easier (it's already provided if you just enable a check) and safer for public repos, as the `GITHUB_TOKEN` is scoped to the repo and not to all your repos like a personal access token.

https://developer.github.com/actions/managing-workflows/storing-secrets/#github-token-secret

**Comment by JamesIves** [comment]
I’d love to, unfortunately there’s an issue with the Github secret provided with actions that prevents Github Pages from rebuilding your site with it, that means that you’ll be able to commit to the branch, but it will never update. It works for private repostitories, but not public ones.

I’m keeping an eye on the situation and will test this again when actions leaves beta.

**Comment by JamesIves** [comment]
I've recently emailed GitHub support, I'll let you know if I hear back!

**Comment by JamesIves** [comment]
Following up on this @gerardabello - here's the response I've received from GitHub.

```
After speaking with the team about this, they let me know that server-to-server requests won't kick off a page build, whether it's creating a commit or explicitly requesting a page build. 

As you've observed, user-to-user server requests (using a personal access token or an OAuth token) can build a Pages project via push or requesting a page build because they're linked to a specific user account.

I see how it would be useful to open this functionality to GitHub Actions, so I've let the team know about this internally.
```

I've also provided GitHub with some additional information about the private repository behavior I mentioned in my initial post. I'll let you know if I hear anything more.

**Comment by JamesIves** [comment]
Still no updates from GitHub on this. I've emailed them twice now with no reply.

**Comment by alex-page** [comment]
Some additional context here:
https://github.com/maxheld83/ghpages/issues/1

**Comment by JamesIves** [comment]
Thanks @alex-page!

**Comment by alex-page** [comment]
Oops that issue only has a bit of context, check the PR out https://github.com/maxheld83/ghpages/pull/18

**Comment by JamesIves** [comment]
I'll keep an eye on this. Doesn't seem possible just yet.

**Comment by JamesIves** [comment]
Fix is coming for this today.

**Comment by JamesIves** [comment]
I've got a PR open for this, but the issue still appears to be present: https://github.com/JamesIves/github-pages-deploy-action/pull/13

**Comment by gerardabello** [comment]
@JamesIves thanks for researching this. Ping me if you need any help.

**Comment by peaceiris** [comment]
FYI. https://github.com/peaceiris/actions-gh-pages/issues/9#issuecomment-529769695

> Community Manager said:
> 
>> The `GITHUB_TOKEN` that is provided as a part of GitHub Actions doesn't have authorization to create any successive events, such as GitHub Pages builds. So while you can push to the `gh-pages` branch using the `GITHUB_TOKEN`, it won't spawn a GitHub Pages build. You'll need to create a personal access token and supply it to your GitHub Action as a secret. 

https://github.com/peaceiris/actions-gh-pages/issues/9#issuecomment-529807695

> Yes, it seems like that's not a bug but a normal behavior in the context of the security rule imposed in Github Actions which is "A workflow can not trigger another workflow".

**Comment by JamesIves** [comment]
https://github.com/JamesIves/github-pages-deploy-action/pull/13#issuecomment-531070655

^ Cross posting this here. I'm going to merge in this feature/PR and point to this issue.

**Comment by dhimmel** [comment]
Quite the limitation that a github action commit cannot trigger another action. Using a personal access token to deploy a single repository is bad practice and the fact that actions require this for something as basic as deploying to gh-pages is evidence that workflows should be able to trigger workflows. Or at least that gh-pages commits should be exempt from this limitation.

Let us know if there are any workarounds that support using `GITHUB_TOKEN` for authentication.

**Comment by peaceiris** [comment]
@dhimmel 
FYI. https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/31266/highlight/true#M743

**Comment by JamesIves** [comment]
The option for using a GitHub token vs an access token is already available in v2 and v3. I'm going to close this issue, please follow this thread to stay up-to-date: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/31266/highlight/true#M743

**Comment by shilangyu** [comment]
It seems github has ditches fixing the `GITHUB_TOKEN`? It's sad because it would be much more convenient :/

**Comment by dhimmel** [comment]
> It seems github has ditched fixing the GITHUB_TOKEN?

Has there been a change in the last few days? Deploying to a branch that then triggers a GitHub Pages build using `GITHUB_TOKEN` has been working for several months, except for [the first deployment as described here](https://github.com/peaceiris/actions-gh-pages/tree/75014632413b319cb87db5b3e54bba2d6a21ac05#%EF%B8%8F-first-deployment-with-github_token). Is this no longer the case?

**Comment by peaceiris** [comment]
It works well.

https://github.com/peaceiris/actions-gh-pages/commits/gh-pages

<img width="664" alt="Screen Shot 2020-05-02 at 2 23 14" src="https://user-images.githubusercontent.com/30958501/80825752-f6275580-8c1b-11ea-982b-d241b1d7a138.png">
