### ISSUE TITLE
`switchToBaseBranch` breaks on force push

### ISSUE THREAD

**Issue by Pike** [JamesIves/github-pages-deploy-action#501]
**Describe the bug**

`switchToBaseBranch` breaks on force push, as it's trying to update on to the previous PR head.

**Reproduce**

Force push to a PR

**Logs**

https://github.com/projectfluent/python-fluent/runs/1408529835?check_suite_focus=true

**Additional Comments**

I'm a bit lost on exactly why it thinks it should update to the old head, but I guess that's part of the beauty of GH event data :-/

**Comment by JamesIves** [comment]
This case seems pretty specific. Is it only when you force push?

**Comment by Pike** [comment]
I've pushed a none-force push to that PR, and I don't know what it's referencing, tbh.

**Comment by JamesIves** [comment]
It's referencing the commit SHA which is provided in the event payload. If it's not working correctly you may need to apply a `BASE_BRANCH` variable so it has something solid to base it off of. I've typically setup deployments in my own workflow to run on merge commits to a specific branch, not on pull request opening. It may require a little bit of research to figure out how to get this to work correctly.

**Comment by Pike** [comment]
This is resolved via #515 by not doing the base branch checkout anymore.
