### ISSUE TITLE
Falsely reports nothing to commit

### ISSUE THREAD

**Issue by Zireael07** [JamesIves/github-pages-deploy-action#502]
**Describe the bug**
I have set up a workflow to auto build and deploy my WASM Rust project. Unfortunately the majority of the time the deploy action fails to notice the files were changed.

**Reproduce**

**Logs**
2nd to last commit: https://github.com/Zireael07/Rust-HTML-roguelike/runs/1414105044?check_suite_focus=true artifact size:  764859 bytes
last commit: https://github.com/Zireael07/Rust-HTML-roguelike/runs/1414289959?check_suite_focus=true artifact size: 764937 bytes 
There's a difference of ~100 bytes in the artifact size, hence there were obviously changes made to the files... but the deploy action on the last commit claims : "There is nothing to commit. Exiting early… "

**Additional Comments**
A (optional) FORCE flag on the action that would do rm -rf . on the working folder before copying files, OR rsync's --delete-before flag as described at https://superuser.com/questions/156664/what-are-the-differences-between-the-rsync-delete-options/156702#156702 would probably help in such cases.

**Comment by JamesIves** [comment]
Try adding `PRESERVE: true` to your workflow. This is likely because you're modifying files in the tree that are tracked so it's being rewinded prior to the deployment, hence the error.

The intention is to make this flag the default option in the next version.

**Comment by Zireael07** [comment]
Yep, that fixes the issue. Should I leave it open so that people find it more easily (maybe for you to pin it to the top - it seems to be something that's tripped some more people, judging from a later skim of the whole issues list?)

**Comment by JamesIves** [comment]
Sure thing, I'll pin the issue.

**Comment by Zireael07** [comment]
I didn't know one could pin closed issues, TIL :)
