### ISSUE TITLE
Handling LFS in checkout or in gh-pages worktree

### ISSUE THREAD

**Issue by Pike** [JamesIves/github-pages-deploy-action#513]
**Describe the bug**

Fix handling of LFS. The current approach doesn't actually fix the problem, AFAICT. Either the `migrate export` needs to run post-commit on the gh-pages worktree, or the checkout needs to be with lfs on.

**Reproduce**

https://github.com/cms-ml/documentation/pull/1 has some info on how to reproduce this, as well as the conversation in #373 .

**Comment by JamesIves** [comment]
Sounds good, and I appreciate the research on this! 👍🏻

**Comment by Pike** [comment]
James merged the no-checkout #515, which resolves this issue in favor of having the checkout action handle lfs.
