### ISSUE TITLE
Make inputs in README lowercase

### ISSUE THREAD

**Issue by JamesIves** [JamesIves/github-pages-deploy-action#531]
About the README:

The github actions use lower-case arguments in documentation, should we do so here, too? `getInput` is case-insensitive, so this should really just be a documentation issue?

_Originally posted by @Pike in https://github.com/JamesIves/github-pages-deploy-action/discussions/524#discussioncomment-150670_

**Comment by Pike** [comment]
I noticed when looking at #547 that action.yml still needs the fixes..

**Comment by JamesIves** [comment]
This has been resolved in the  v4 branch already so I'm going to close out this ticket.
