### ISSUE TITLE
Fatal: reference is not a tree : [sha]

### ISSUE THREAD

**Issue by fanhaoyuan** [JamesIves/github-pages-deploy-action#532]
When I submitted code on the current branch Actions before using the Actions, this problem arises because the hash value that triggers the Actions is inconsistent with the hash value of the current branch。

example:
hash value triggering the actions：20822271f44c3c53363d71dc54e40671d9c68975

first step：
first actions commit and push, Latest hash value had changed： 20822271f44c3c53363d71dc54e40671d9c68975 --> 3a336fe770e45274e1a0bc694a3e8c80317bb71f

second step:
this action' defaultBranch will Locate  '20822271f44c3c53363d71dc54e40671d9c68975'.

third step:

when exceute git checkout --progress --force 20822271f44c3c53363d71dc54e40671d9c68975, error has show.

```bash
/usr/bin/git checkout --progress --force 20822271f44c3c53363d71dc54e40671d9c68975
fatal: reference is not a tree: 20822271f44c3c53363d71dc54e40671d9c68975
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌
```

I think we should check whether it's the latest hash value before checkout.

**Comment by Pike** [comment]
Is that on a PR? If so, I've run into that myself. The background is where the PR commits are on gh, and how the deploy action fetches.

The checkout code is going away with v4, so this should stop being a problem. The checkout action handles the remotes well.

**Comment by fanhaoyuan** [comment]
I can reproduce that.Now I have solved this problem. By getting the latest commit hash and comparing it with the hash value of the current triggering action, I changed the consistency of the check-out code before and after.

**Comment by JamesIves** [comment]
What use case is this trying to solve? I feel like the `PRESERVE` option will fit the use case here but I can't be certain.

As @Pike mentioned the checkout code is being removed in version 4, I'm a little hesitant to adjust how this works right now with an active workaround in place.

**Comment by fanhaoyuan** [comment]
I tested <code>PRESERVE</code>,but still doesn't work.

Here is a scenario where I need to manipulate the content before packing the pages, such as adding logs, modifying routing, etc. Then I updated the code after the last step, but I released it after packing, but it was not the latest submission, and then there was an error.

As a result, the package release depends on the last actions submission.

I've got a couple of test results and a repetition of previous questions  [git-pages-deploy-test](https://github.com/fanhaoyuan/gh-pages-workflow-test/actions)

**Comment by JamesIves** [comment]
@fanhaoyuan Can you try this again by pointing your workflow to `releases/v4`? We've been working on a new version and I'm pretty sure this issue should be resolved with it. It's officially due out later today but you're able to try it early by pointing to the release branch instead of a tagged version.

If this issue persists in v4 please open a new issue and I'll take care of it, otherwise I'm going to close this as wontfix.
