### ISSUE TITLE
DRY_RUN fails on missing permissions

### ISSUE THREAD

**Issue by Pike** [JamesIves/github-pages-deploy-action#536]
**Describe the bug**

The newly-addded `DRY_RUN` option doesn't work as I expected it to. The push command actually does check for permissions, and then fails

**Reproduce**

https://github.com/JamesIves/github-pages-deploy-action/pull/505/checks?check_run_id=1524896089

**Logs**

https://github.com/JamesIves/github-pages-deploy-action/pull/505/checks?check_run_id=1524896089

**Additional Comments**

I'm leaning towards not pushing at all for `DRY_RUN`. That sounds more fool-proof than trying to catch the security error in some sorta smart way?

**Comment by JamesIves** [comment]
That's really bizarre, it must be because it's trying to access the secret at all and it's causing the workflow to hard fail. It's not ideal, but wrapping these commands are probably better than having no tests at all.

**Comment by Pike** [comment]
In #505 I changed sooooo many things that there's actually only one `git push` left, which is then nicely wrapped.

**Comment by Pike** [comment]
This  got fixed with #505.
