### ISSUE TITLE
Build fails if deploy files aren't new

### ISSUE THREAD

**Issue by shilangyu** [JamesIves/github-pages-deploy-action#54]
**Describe the bug**

If the action is ran and no deploy file has changed the build will fail.

**Reproduce**

- Create a workflow with this action using `releases/v3` that triggers on `push`
- Push something unrelated to the deploy (for example a change in README)
- The ci will fail

**Expected behavior**

The build doesnt fail *or* Im able to tell the action to not fail on clean git trees (however i think it should be the default)

**Screenshots**

![image](https://user-images.githubusercontent.com/29288116/69182609-ab080300-0b11-11ea-94f3-ab6889ac3539.png)

**Comment by JamesIves** [comment]
The build should pass in this case. I'll push up a fix for this here shortly.

**Comment by JamesIves** [comment]
PR: https://github.com/JamesIves/github-pages-deploy-action/pull/55

**Comment by shilangyu** [comment]
![image](https://user-images.githubusercontent.com/29288116/69188764-713cf980-0b1d-11ea-9453-40904774ac7b.png)
yup!

**Comment by JamesIves** [comment]
This has been deployed and released with `3.0.1`, it's available as part of `releases/v3`. Thanks for the report!
