### ISSUE TITLE
Better mock for unittests

### ISSUE THREAD

**Issue by Pike** [JamesIves/github-pages-deploy-action#544]
**Describe the bug**

Right now, we use `action.isTest` to signal scenarios to the unit tests. In #505 we talked about better mocking. Filing an issue to track  this.

@JamesIves, you sounded like you have an indea?

My thinking behind `GitCheckout` was to help with that, and has evolved a bit since then. From a mocking-point-of-view, I like the idea to have a module with functions like `gitLsRemote` (or `git_ls_remote` with some linting exceptions), and classes for the params for each. The params could be used in tests via `jest.requireActual`.

Maybe even a higher abstraction for the changed-files check?

**Comment by JamesIves** [comment]
Yeah, it's only used to signal that a branch existed. But in hindsight it would of been better to mock the `execute` call so when it's called with the the `git ls-remote` arg it returned something that mimicked what `git ls-remote` would actually return. That way we wouldn't need to have a specific argument to signal this. 

This was setup a while ago when I didn't have much experience with Jest's module mocking so it was a pretty hacky workaround.
