### ISSUE TITLE
Issues with "rsync" on windows

### ISSUE THREAD

**Issue by yanntm** [JamesIves/github-pages-deploy-action#575]
**Describe the bug**

On windows, there seems to be an issue with "rsync" being used when it is not available in powershell.

**Reproduce**

Run with `runs-on: windows-latest` flag to reproduce.

**Logs**

Some relevant traces, full trace is here :  https://github.com/lip6/libDDD/runs/1742169007?check_suite_focus=true
```
HEAD is now at 21e2334 compress image
"C:\Program Files\Git\bin\git.exe" fetch ***github.com/lip6/libDDD.git
From https://github.com/lip6/libDDD
 * branch            HEAD       -> FETCH_HEAD
"C:\Program Files\Git\bin\git.exe" worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/Windows
Preparing worktree (detached HEAD 56379c9)
HEAD is now at 56379c9 Initial Windows commit
Running post deployment cleanup jobs… 🗑️
"C:\Program Files\Git\bin\git.exe" worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: Unable to locate executable file: rsync. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file. ❌
Deployment failed! ❌
```

**Additional Comments**

My source workflow file is this one : https://github.com/lip6/libDDD/blob/21e2334acaa90f8d2d7215a3d4e0f3716fc85170/.github/workflows/windows.yml

**Comment by JamesIves** [comment]
Sadly rsync is not compatible with Windows, I've looked into replacing it with the upcoming v4 release but there's not really anything that can easily replace it. [There is a Windows version of rsync](https://itefix.net/cwrsync) but I don't believe you can install it within a workflow environment trivially.

There is a workaround however under Operating Support in the README: https://github.com/JamesIves/github-pages-deploy-action#operating-system-support-

**Comment by yanntm** [comment]
Thanks for the answer, I've been fiddling around with another path that uses the rsync package provided by MSYS (that is deployed by default on windows). 
So I've added the following to my yml :
```
    - name: install rsync
      run: C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm rsync ; which rsync "
    - name: non official add path version for windows
      run: echo "##[add-path]C:\msys64\usr\bin"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'       
```

the `which` can obviously be removed if it works, this was debug mode.
It was pretty difficult to find a way to update the path so your command sees it, I resorted to the ugly `ACTIONS_ALLOW_UNSECURE_COMMANDS` I'd be happy to find another syntax that works.

anyway, with these additional steps in the job, your command finds "rsync" when needed (:birthday:) but then I reach this new error : 

```
    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using GitHub Token… 🔑
Configuring git…
"C:\Program Files\Git\bin\git.exe" init
Reinitialized existing Git repository in D:/a/libDDD/libDDD/.git/
"C:\Program Files\Git\bin\git.exe" config user.name yanntm
....
....
From https://github.com/lip6/libDDD
 * branch              HEAD       -> FETCH_HEAD
"C:\Program Files\Git\bin\git.exe" worktree add --checkout github-pages-deploy-action-temp-deployment-folder origin/Windows
Preparing worktree (detached HEAD 56379c94)
HEAD is now at 56379c94 Initial Windows commit
C:\msys64\usr\bin\rsync.exe -q -av --checksum --progress D:\a\libDDD\libDDD\website\/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
ssh: Could not resolve hostname d: No such host is known. 
rsync: [Receiver] safe_read failed to read 4 bytes: Connection reset by peer (104)
rsync error: unexplained error (code 255) at io.c(276) [Receiver=3.2.3]
Running post deployment cleanup jobs… 🗑️
"C:\Program Files\Git\bin\git.exe" worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process 'C:\msys64\usr\bin\rsync.exe' failed with exit code 255 ❌
Deployment failed! ❌
```

So, much much better, we are almost there except the path has backslashes in them but the rsync version taken from MSYS does not support them. 
So it reads "d" or maybe "d:"  and cuts on the backslash it seems.

Fortunately just reversing the slashes gives a path that should work.
In the first part of the trace we can see the path `D:/a/libddd/...` which is legal.

Maybe we could protect the function 

https://github.com/JamesIves/github-pages-deploy-action/blob/65691af8c1db8541206091bcf3278dd7867fb82a/src/git.ts#L216

to front-slashify any backslashes in the variable `${action.folderPath}/` ? Or canonicalize it in some more elegant way.

thanks for your work on this tool.

**Comment by yanntm** [comment]
This all  a bit too complex, also the problem might be with the version of ssh rsync uses, your other solution (with a separate step and artifacts) works well enough for me.
I'll close this issue, thanks for your time.
