### ISSUE TITLE
Reference original repository commit when pushing to other repo

### ISSUE THREAD

**Issue by Pike** [JamesIves/github-pages-deploy-action#582]
**Describe the bug**
While looking at https://github.com/JamesIves/test-repo/commit/8b801ae4a2027901e3df4097c2bf46523baba010, I noticed that the commit isn't linked because it's in a different repo.

We should link this up like JamesIves/test-repo@8b801ae4a2027901e3df4097c2bf46523baba010, I guess.

**Comment by JamesIves** [comment]
Good catch!

**Comment by JamesIves** [comment]
PR: https://github.com/JamesIves/github-pages-deploy-action/pull/583
