### ISSUE TITLE
3.0 Allow to clean up existing files in target branch

### ISSUE THREAD

**Issue by ISDThalackDalhar** [JamesIves/github-pages-deploy-action#60]
**Is your feature request related to a problem? Please describe.**

Some frameworks generate js files with a content hash, to provide better cache management. Since all existing files are left intact on the target branch, this means that the target branch will only increase in size.

Now I'm aware an option would be to disable content hash tags, but it also applies to files that are no longer needed.

Would it be possible to add a flag to have this action clean up files that no longer exist in the source folder?

**Describe the solution you'd like**

Ideally, instead of copying over the source folder on top of the target branch, a rsync with a delete option so that files that no longer exist in the source folder are removed from the branch

**Additional Comments**

N/A

**Comment by JamesIves** [comment]
I'm happy to add this, and I think this covers the best of both worlds between version 2 and 3. 

This is where the `rsync` action occurs that pushes over the files into the folder that gets deployed to Git. Is there a specific command you have in mind that will handle this?

**Comment by ISDThalackDalhar** [comment]
Probably when the feature flag is enabled, a rsync with the --delete flag would suffice. It removes all files in the target directory that no longer exists in the source directory.

the --delete flag comes in three flavors:

`--delete` deletes files _during_ transfer between source and target
`--delete-before` deletes removed files before transferring the modified content from source to target
`--delete-after` deletes removed files after transferring the modified content from source to target.

I don't think there's any benefit of either one over the other, so I would probably go for the 'default' --delete option.

**Comment by JamesIves** [comment]
Excellent. I'll give this a try later tonight and let you know when it's available for testing.

**Comment by JamesIves** [comment]
@ISDThalackDalhar This is now available if you point your workflow to `releases/v3-test` and add this to your config.

```
with:
  CLEAN: true
```

Here's the PR: https://github.com/JamesIves/github-pages-deploy-action/pull/63

**Comment by ISDThalackDalhar** [comment]
Thanks for the quick turnaround, v3-test is currently being tested with both #62 and #63, will let you know later today how they behaved.

**Comment by ISDThalackDalhar** [comment]
Have it running for a few hours, it seems to be working just fine :+1:

**Comment by JamesIves** [comment]
Great, thanks for testing!
