### ISSUE TITLE
3.0 Git reinitalization error, build continues

### ISSUE THREAD

**Issue by ISDThalackDalhar** [JamesIves/github-pages-deploy-action#61]
**Describe the bug**

During a scheduled run of my workflow an error is generated during the git init step, however, the build itself continues to run just fine.

The log of the run can be seen here: https://github.com/eve-lore/gallente-elections/runs/314791864

**Reproduce**

See link above

**Expected behavior**

While I'm not sure if that would have actually been an error (I also cannot see where it was actually triggered), I would likely expect it to be either ignored, or aborted.

**Screenshots**

See link above.

**Additional Comments**

N/A

**Comment by JamesIves** [comment]
Resolved: https://github.com/JamesIves/github-pages-deploy-action/pull/62

**Comment by ISDThalackDalhar** [comment]
Have it running for a few hours, it seems to be working just fine :+1:

**Comment by JamesIves** [comment]
Thanks again for the report and testing, this is now available in `releases/v3` in the `3.0.2` release: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.0.2
