### ISSUE TITLE
RangeError: Invalid string length with large repositories 

### ISSUE THREAD

**Issue by keichan34** [JamesIves/github-pages-deploy-action#644]
## Describe the bug

When there are a lot of files in the repository (in our case, 30,000+), the `output` buffer in `execute.ts` can become longer than `buffer.constants.MAX_STRING_LENGTH` and fail with `RangeError: Invalid string length`.

## Reproduction Steps
Deploy a lot of files 

## Logs
```

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
Git configured… 🔧
Starting to commit changes…
Creating worktree…
Checking if there are files to commit…
/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.1.0/lib/execute.js:38
    output += data.toString().trim();
                              ^

RangeError: Invalid string length
    at Object.stdout (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.1.0/lib/execute.js:38:31)
    at Socket.<anonymous> (/home/runner/work/_actions/JamesIves/github-pages-deploy-action/4.1.0/node_modules/@actions/exec/lib/toolrunner.js:400:52)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

https://github.com/agro-env/meteo-1978/runs/2145235102?check_suite_focus=true

## Additional Comments

Based on a cursory look at the code, it seems like the output of the action is only being used for tests? Would there be any adverse effects if this was disabled when not running tests? If not, I'd be happy to submit a PR for this.

**Comment by JamesIves** [comment]
That's a lot of files! 

I believe this would need testing to ensure that it doesn't have any unintended side effects. If you'd like to submit a PR I can run the integration suite on the branch to ensure there's no issues.

**Comment by JamesIves** [comment]
I've got a potential fix for this available on the `releases/v4-beta` branch.

If you'd like to test it out you can point your workflow to the following: `JamesIves/github-pages-deploy-action@releases/v4-beta`.  Let me know if that works and I'll push it into the next release.

**Comment by garazdawi** [comment]
I just got the same error as this running on `4.1.3`: https://github.com/garazdawi/jekyll-test/runs/2719439035

I "only" have 16000 files in the repo :)
