### ISSUE TITLE
clean-exclude option not recognized

### ISSUE THREAD

**Issue by DanielHabenicht** [JamesIves/github-pages-deploy-action#664]
## Describe the bug
`clean-exclude` option in the documentation produces the warning: 
```bash
Unexpected input(s) 'clean-exclude', valid inputs are ['SSH', 'ACCESS_TOKEN', 'GITHUB_TOKEN', 'BRANCH', 'FOLDER', 'TARGET_FOLDER', 'BASE_BRANCH', 'COMMIT_MESSAGE', 'CLEAN', 'CLEAN_EXCLUDE', 'GIT_CONFIG_NAME', 'GIT_CONFIG_EMAIL', 'REPOSITORY_NAME', 'WORKSPACE', 'SINGLE_COMMIT', 'LFS', 'SILENT', 'PRESERVE']
```

## Reproduction Steps
Use this config
```bash
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: covquestions-js/docs
          clean: true
          # Ignore API Files
          clean-exclude: |
            questionnaires.json
            questionnaires/**

```

## Additional Comments
It works with the parameter `clean_exclude`. Maybe it also affects other properties.

Should the Documentation be changed or the code?

**Comment by JamesIves** [comment]
The hyphenated options are available in version 4, [please follow the migration guide](https://github.com/JamesIves/github-pages-deploy-action/discussions/592) to update as version 3 is no longer supported:.

The [current version](https://github.com/JamesIves/github-pages-deploy-action/releases) is `4.1.1` (You can replace the `4.0.0` in the examples with it)

**Comment by DanielHabenicht** [comment]
Thanks, works like a charm. Sorry for not recognizing the newer version...
