### ISSUE TITLE
private repository fatal error: could not read Username

### ISSUE THREAD

**Issue by tao** [JamesIves/github-pages-deploy-action#70]
**Describe the bug**

When deploying my static site to GitHub Pages, it works if the repository is public but as soon as I switch over to private it's throwing a bunch of issues.

**Reproduce**

The demo repository is here: https://github.com/tao/jigsaw-deploy-bug 

**Expected behavior**

I was working on this issue for a while and figured out it disappeared on my test repository when it was public, but these issues come up when made private, the issue thrown is:

```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    ACCESS_TOKEN: ***
    BASE_BRANCH: master
    BRANCH: gh-pages
    FOLDER: build_production
Reinitialized existing Git repository in /home/runner/work/jigsaw-deploy-bug/jigsaw-deploy-bug/.git/
git config user.name tao
git config user.email tao@users.noreply.github.com
git ls-remote --heads https://***@github.com/tao/jigsaw-deploy-bug.git gh-pages | wc -l
49f0c117cd645d02e0a4feecde33e81223cadb38	refs/heads/gh-pages
git checkout master
Switched to a new branch 'master'
M	source/assets/build/css/main.css
M	source/assets/build/js/main.js
M	source/assets/build/mix-manifest.json
Branch 'master' set up to track remote branch 'master' from 'origin'.
git fetch origin
fatal: could not read Username for 'https://github.com': No such device or address
##[error]The process 'git' failed with exit code 128
Completed Deployment
##[error]Node run failed with exit code 1
```

I've tried this with GITHUB_TOKEN and ACCESS_TOKEN and the errors are a bit different, with GITHUB_TOKEN the response is:

```
Run JamesIves/github-pages-deploy-action@releases/v3
  with:
    ACCESS_TOKEN: ***
    BASE_BRANCH: master
    BRANCH: gh-pages
    FOLDER: build_production
git init
Reinitialized existing Git repository in /home/runner/work/jigsaw-deploy-bug/jigsaw-deploy-bug/.git/
git config user.name tao
git config user.email tao@users.noreply.github.com
git ls-remote --heads https://***@github.com/tao//jigsaw-deploy-bug.git gh-pages | wc -l
fatal: could not read Password for 'https://***@github.com': No such device or address
##[error]The process 'git' failed with exit code 128
Completed Deployment
##[error]Node run failed with exit code 1
```

**Additional Comments**

It's my first time using GitHub Actions and Github Pages, so there could be something small I'm missing but it would be great if I could run this from a private repo.

The permissions given to ACCESS_TOKEN are [repo:all] and [read:public_key]

**Comment by JamesIves** [comment]
Thanks for the report! 

This appears to be a bug, but I think it's easily fixed. In the first example it looks like `git fetch origin` is the culprit. I've made a small change to how this command is executed and pushed it up to `JamesIves/github-pages-deploy-action@releases/v3-test` if you'd like to test it out.

In the second example you need to change your configuration so it reads the following if you want to use `GITHUB_TOKEN`. Keep in mind there's still a number of issues with using this token, but the last I heard it should work for private repositories.

```yml
with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Here's the pull request: https://github.com/JamesIves/github-pages-deploy-action/pulls

**Comment by tao** [comment]
Thanks, that's fixed the deploy for both ACCESS_TOKEN and GITHUB_TOKEN.

**Comment by JamesIves** [comment]
Thanks for testing.

Tagged and released to `releases/v3`: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.0.4
