### ISSUE TITLE
Push is rejected

### ISSUE THREAD

**Issue by CommanderTvis** [JamesIves/github-pages-deploy-action#718]
## Describe the bug

Pushs from the action to `gh-pages` branch are rejected by the remote. It may be related to the GitHub outage (https://www.githubstatus.com).

## Logs

https://github.com/CommanderTvis/exams-guide/runs/2594536236

**Comment by davetapley** [comment]
I saw the same on https://github.com/davetapley/helium-tax/runs/2594633023

Incident resolved and subsequent push worked ✅ 
https://www.githubstatus.com/incidents/zbpwygxwb3gw

**Comment by f-w** [comment]
I got _remote: fatal error in commit_refs_ in the workflow logs. This happened only recently.
In my case I have setup branch protection rules to _Require linear history_, which preventing forced push, as well as _Include administrators_. But the rule applies only to branches other than gh-pages. After I disable the rule, the workflow worked.
When the rule was in effect, if I forced push to gh-pages manually from localhost, it worked.

**Comment by CommanderTvis** [comment]
> I saw the same on https://github.com/davetapley/helium-tax/runs/2594633023
> 
> Incident resolved and subsequent push worked 
> https://www.githubstatus.com/incidents/zbpwygxwb3gw

Everything works after the outage was resolved, closing the issue.
