### ISSUE TITLE
Edit documentation for "win" case: drop token

### ISSUE THREAD

**Issue by yanntm** [JamesIves/github-pages-deploy-action#734]
## Describe the bug

The documentation here : https://github.com/JamesIves/github-pages-deploy-action#operating-system-support-

suggests to use the line 

        with:
          token: ${{ secrets.ACCESS_TOKEN }}

I believe it is no longer necessary, in this scenario the target repo is the same we are working with, so letting the token default to current session token is fine.

## Reproduction Steps

This small sample project works without specifying a token
https://github.com/yanntm/TestDeployActionWin

## Logs

Check the Actions : https://github.com/yanntm/TestDeployActionWin/actions
Or maybe the gh-pages branch : https://github.com/yanntm/TestDeployActionWin/tree/gh-pages

It works as expected without token in the https://github.com/yanntm/TestDeployActionWin/blob/master/.github/workflows/windows.yml

## Additional Comments

Thanks for this tool.

**Comment by JamesIves** [comment]
Thanks, this edit will be made with release 4.1.4.
