### ISSUE TITLE
`CLEAN: true` not working

### ISSUE THREAD

**Issue by jhpratt** [JamesIves/github-pages-deploy-action#75]
I am currently building documentation for time-rs/time and publishing using this action. In the [relevant workflow](https://github.com/time-rs/time/blob/master/.github/workflows/docs.yaml), I set `CLEAN: true` as indicated by the README. However, the history still persists (see the commits for the [`gh-pages` branch](https://github.com/time-rs/time/commits/gh-pages)).

Am I doing something wrong here?

**Comment by JamesIves** [comment]
`CLEAN: true` does not wipe out the git history. It just ensures that any hashed files that are generated by a previous deployment are deleted so it doesn't fill up your branch with unused files.

You may want to look into using the `releases/v2` branch if this is what you need.

**Comment by jhpratt** [comment]
Ah, gotcha. The history isn't a big deal, but does clutter the graph view of the git log.

Thanks for the quick response.
