### ISSUE TITLE
Publish new NPM version.

### ISSUE THREAD

**Issue by XAMPPRocky** [JamesIves/github-pages-deploy-action#752]
Hello, I was updating my action https://github.com/XAMPPRocky/deploy-mdbook which depends on this action, the current npm version no longer works because it's using deprecated features (specifically `set-env`). Would it be possible to publish the latest version of the action on npm?

**Comment by JamesIves** [comment]
Every version is cross published on the [GitHub](https://github.com/JamesIves/github-pages-deploy-action/packages/229985) and [npmjs registry](https://www.npmjs.com/package/@jamesives/github-pages-deploy-action) already!

**Comment by XAMPPRocky** [comment]
@JamesIves Ah, I see now. I'm using it as a top-level dependency `github-pages-deploy-action`, not `@jamesives/github-pages-deploy-action`, the former of which hasn't been updated in a year. Thanks for clarifying!

**Comment by JamesIves** [comment]
Ah yep, this was changed about a year ago to support the GitHub registry which requires scoping.

**Comment by XAMPPRocky** [comment]
Hmm, when I try to install it I get the following error.

```
npm i @jamesives/github-pages-deploy-action

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@JamesIves%2fgithub-pages-deploy-action - Not found
npm ERR! 404
npm ERR! 404  '@JamesIves/github-pages-deploy-action@^4.1.4' is not in the npm registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by JamesIves** [comment]
That's weird, maybe something to do with your npm version? Worked for me:

```
Jamess-MBP-2:ChaCha ives$ yarn add @jamesives/github-pages-deploy-action
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 18 new dependencies.
info Direct dependencies
└─ @jamesives/github-pages-deploy-action@4.1.4
info All dependencies
├─ @actions/core@1.3.0
├─ @actions/exec@1.0.4
├─ @actions/github@5.0.0
├─ @actions/http-client@1.0.11
├─ @actions/io@1.1.0
├─ @jamesives/github-pages-deploy-action@4.1.4
├─ @octokit/auth-token@2.4.5
├─ @octokit/core@3.4.0
├─ @octokit/endpoint@6.0.11
├─ @octokit/graphql@4.6.2
├─ @octokit/openapi-types@7.3.0
├─ @octokit/plugin-paginate-rest@2.13.3
├─ @octokit/plugin-rest-endpoint-methods@5.3.1
├─ @octokit/request-error@2.0.5
├─ @octokit/request@5.5.0
├─ before-after-hook@2.2.2
├─ deprecation@2.3.1
└─ tunnel@0.0.6
✨  Done in 9.71s.
```
