### ISSUE TITLE
当我使用非master分支推送 会报错

### ISSUE THREAD

**Issue by roftLin** [JamesIves/github-pages-deploy-action#763]
## Describe the bug

https://github.com/roftLin/vue-component/runs/2827195761?check_suite_focus=true 

## Logs

Setting up libjq1:amd64 (1.5+dfsg-1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up jq (1.5+dfsg-1.3) ...
Reinitialized existing Git repository in /github/workspace/.git/
error: pathspec 'master' did not match any file(s) known to git.
Deploying to GitHub...
fatal: pathspec 'docs' did not match any files

**Comment by JamesIves** [comment]
Please re open your issue with more details. The link you provided is also private.
