### ISSUE TITLE
Workspace should return to normal after deployment

### ISSUE THREAD

**Issue by brockfanning** [JamesIves/github-pages-deploy-action#89]
**Describe the bug**

After the deployment, I think that the repo needs to be left exactly as it was before. Right now there is some discrepancy that can cause problems in subsequent steps.

**Reproduce**

In my case I'm looking a particular folder, before and after the deployment, and seeing a difference. The workflow is [here](https://github.com/brockfanning/sdg-data-cambodia/blob/develop/.github/workflows/deploy-staging.yml). The evidence of the discrepancy is in the Github Actions output [here](https://github.com/brockfanning/sdg-data-cambodia/commit/e351da504cec471750d29895b076174a510d5373/checks?check_suite_id=369930460). Compare the sections "scripts folder before deploy" and "scripts folder after deploy".

**Expected behavior**

In the example above, the output of "scripts folder before deploy" and "scripts folder after deploy" should be the same.

**Additional Comments**

The failure in that linked workflow shows an example of how this can cause a problem. In this case, it's preventing the official "cache" action's "Post" step from working.

**Comment by JamesIves** [comment]
I'm a little confused about why your workflow is failing as I don't have much insight into what those subsequent steps are doing. 

The deployment action does create a temporary work space for a git command it runs which you can see [here](https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/git.ts#L80-L83). Are you requesting that this temp folder gets deleted once the deployment has been completed?

**Comment by brockfanning** [comment]
Thanks for the quick reply @JamesIves. My only concern is the difference between the output under my "scripts folder before deploy" and "scripts folder after deploy". Do you know of any reason that this would happen? My goal is for this folder to be the same after the deploy as it was before. Hope that makes sense - sorry I'm not sure if this is related to the temp work space.

**Comment by JamesIves** [comment]
I have a theory on this. I'm guessing because it checks out a temporary branch with _just_ the deployment changes prior to pushing is why you're seeing such a large discrepancy here. 

I think two things need to happen after the deployment is done.

1. It switches back to the base branch (master if it's not specified)
2. It needs to _delete_ the temporary deployment folder which is created. 

Can you run this workflow again using `JamesIves/github-pages-deploy-action@releases/v3-test`? I've pushed up a change which may fix this.

**Comment by brockfanning** [comment]
Thanks again - unfortunately it doesn't look like it fixed it. [Here](https://github.com/brockfanning/sdg-data-cambodia/commit/59aeec143b04464e4d23117ce278987255981274/checks?check_suite_id=369962238) is the latest output. To simplify things I removed the "cache" stuff. The contents of that folder still seems to be different before/after the deploy.

**Comment by brockfanning** [comment]
Oh, I see that you said it switches back to the "base branch". Is that what I configured as BASE_BRANCH [here](https://github.com/brockfanning/sdg-data-cambodia/blob/develop/.github/workflows/deploy-staging.yml#L41)? If so, that's not what I would prefer. It should go back to the branch that was checked out for the build. So, whatever got checked out during the "actions/checkout" branch.

**Comment by JamesIves** [comment]
`actions/checkout` checks out the default branch of the repo. Do you know of a git command that switches you back to the default branch?

**Comment by brockfanning** [comment]
From what I can tell [here](https://github.com/actions/checkout) it depends on what event triggered the workflow. Maybe we could use `$GITHUB_SHA` here?

**Comment by JamesIves** [comment]
@brockfanning Pushed up another update for this. Let me know if that works for you.

**Comment by brockfanning** [comment]
Looks like that worked! The contents of that folder are the same now before and after the deploy ([link to output](https://github.com/brockfanning/sdg-data-cambodia/commit/355b6f90dd033e641c2e2c6b69abd18c7cdae877/checks?check_suite_id=369977303)). :+1:

**Comment by JamesIves** [comment]
Perfect! Let me clean up this PR a little bit first and I'll cut a new release. I'll let you know when that's done so you can revert back to using `releases/v3`.

**Comment by JamesIves** [comment]
This is now available in `releases/v3` and versioned as `3.1.0`. Thanks for reporting this!

https://github.com/JamesIves/github-pages-deploy-action/releases/tag/3.1.0
