### ISSUE TITLE
File name starting with number gets deleted

### ISSUE THREAD

**Issue by tommypepsi** [JamesIves/github-pages-deploy-action#910]
## Describe the bug

Files that starts with a number are getting deleted on deployment. This seems to be happening only when the file is at the root of the folder being deployed and not when the file is in a sub directory.

**Comment by JamesIves** [comment]
Please can you provide some more details such as logs and file name examples?

**Comment by tommypepsi** [comment]
Sorry, just figured it out. Seems it was related to an action that was running just before this one that was cleaning up some files!
