### ISSUE TITLE
Error in redirection to the dependabot page

### ISSUE THREAD

**Issue by anushbhatia** [JamesIves/github-pages-deploy-action#923]
### When you try to click the dependabot link in the Readme.MD redirects you to the 404 page not found.
Below is attached the relevant video to that.
![screen-capture](https://user-images.githubusercontent.com/40017559/141651420-e5f6f4d6-e974-4ee6-b5ce-20be56b8353f.gif)

## Reproduction Steps

- [ ] 1.  We can modify the link to either https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates.

- [ ] 2. Refactoring the text inside the readme so that person using it will be able to understand the working of it.

We could also attach the following link in the readme https://github.com/features/security

## Additional Comments

Recently the dependabot has moved from a GitHub marketplace service to an officially acquired service in the settings tab. So hereby it requires updating the Readme.
More information can be read at: https://github.com/dependabot/dependabot-core

**Comment by JamesIves** [comment]
I like the idea of 1 along with a mention in the security documentation. Would you like to create a pull request?

**Comment by anushbhatia** [comment]
Sure gladly would do so 😇.  Could you assign me this.
