### ISSUE TITLE
Create any specified BASE_BRANCH if it does not exists

### ISSUE THREAD

**Issue by brockfanning** [JamesIves/github-pages-deploy-action#93]
**Is your feature request related to a problem? Please describe.**

I would like to be able to provide a "template repository" that would allow non-technical users to quickly create a repo and have GitHub pages deployments working without much trouble. The problem is that for brand new repos, only the default branch exists - so there is no "gh-pages" branch. So users have to create that branch manually.

Right now the BRANCH does get created if it does not exist. But if BASE_BRANCH does not exist, the step fails.

**Describe the solution you'd like**

If the BASE_BRANCH does not exist, I would like this step to create it.

**Comment by JamesIves** [comment]
Could you elaborate on the use case of this more? The base branch option is technically not required as it will base the deployment on the current commit, the branch will be gh-pages in most use cases, and if that doesn’t exist the step will automatically create it. 

Why do you need it to create a new branch from the current commit?

**Comment by brockfanning** [comment]
Actually I think it's OK to close this - I was thinking before that the automated commits would be unnecessarily complicated if BASE_BRANCH was different from BRANCH. But I just tested and the commits look fine if I set BRANCH to 'gh-pages' and BASE_BRANCH to 'develop'. (Side question - I guess I'm confused about what purpose/effect BASE_BRANCH has. I seems like it could be any existing branch, and the result would be the same. But I'm probably missing/misunderstanding something.)

**Comment by JamesIves** [comment]
`BASE_BRANCH` is used if you need to make a deployment from another branch besides the one you're committing to, or if you're using a scheduled job which doesn't necessarily have a commit SHA tied to it. An example of this would be if you store your page on the `site` branch, but each time you make a commit to `master` you need to make a deployment. This would allow the action to checkout `site` and push it to whatever the `BRANCH` of your choosing is, for instance `gh-pages`. It's a pretty niche feature.

In `3.1.0` I changed it so `BASE_BRANCH` now defaults to the current commit SHA, only if it doesn't exist will it default to `master`.  This means that in the majority of use cases you don't need to specify a `BASE_BRANCH` at all. If your action is setup to deploy to `gh-pages` on push to develop, then you can just omit that configuration.

Hopefully that clears it up! I am going to add a change to the README to clarify this a little better.

**Comment by brockfanning** [comment]
Aha, that makes sense. I'll go ahead and close this.
