### ISSUE TITLE
Pusher email seems to be missing

### ISSUE THREAD

**Issue by plainheart** [JamesIves/github-pages-deploy-action#937]
## Describe the bug

Hi, I'm not sure why the [Github commit page](https://github.com/apache/echarts-website/commits/asf-site) doesn't show the pusher's avatar recently, but I guess it is related to #926.

## Reproduction Steps

Manually run the action

## Logs

Please check [here](https://github.com/apache/echarts-website/runs/4330614565?check_suite_focus=true#step:11:26) for the log. We can see the pusher's email is empty and it's different from the [previous one](https://github.com/apache/echarts-website/runs/4064033324?check_suite_focus=true#step:11:26).

## Additional Comments

It can work well about 3 weeks ago.

**Comment by JamesIves** [comment]
This has been resolved as of version `4.1.7`: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/4.1.7

**Comment by plainheart** [comment]
Thanks a lot for the quick fix! Really appreciate it!
