### ISSUE TITLE
Jekyll environment variables not working

### ISSUE THREAD

**Issue by yuceltoluyag** [JamesIves/github-pages-deploy-action#962]
- https://jekyllrb.com/docs/configuration/environments/
- https://github.com/yuceltoluyag/yuceltoluyag.github.io/blob/main/_layouts/post.html#L71
-  https://yuceltoluyag.github.io/terminatorgitcurlfish-yukleme/   (test page) Google adsense should appear on the page, but it doesn't. If you examine the source codes, you can see that the codes of google adsense are not coming.

I don't know if the ".jekyll" file has any effect. I had strange problems today. I also removed the ".jekyll" file, nothing changed. 

- https://github.com/yuceltoluyag/yuceltoluyag.github.io/commit/4477caddb1d5663e2cfeb118c70ed2fd8e9986e5

**Comment by JamesIves** [comment]
The deployment action doesn't handle the build process of Jekyll pages, only the moving of the files to your deployment branch. If something isn't building correctly you may need to explore your repositories secret settings.

**Comment by yuceltoluyag** [comment]
> The deployment action doesn't handle the build process of Jekyll pages, only the moving of the files to your deployment branch. If something isn't building correctly you may need to explore your repositories secret settings.

Yes you are right, i thought it would automatically detect when the project goes live
for testing I added the following line, everything worked fine

* https://github.com/yuceltoluyag/yuceltoluyag.github.io/blob/e0356797bc6b2db43e430c9da74bc504fce2c285/.github/workflows/gh-pages.deploy.yml#L34
