### ISSUE TITLE
.nojekyll when specifying sub target-folder in remote repo

### ISSUE THREAD

**Issue by fbrier** [JamesIves/github-pages-deploy-action#963]
## Description

The .nojekyll is still allowing HTML files beginning with an underscore ("_") to be ignored. My Github Action is copying Doxygen pages to a target-folder of a remote repository. When remote repo is cloned and after the rsync of the generated documentation to the target-folder, the .nojekyll file is now in a subdirectory of the Github pages, no longer in the root. So it will be ignored, correct? Jekyll will execute and not copy the files beginning with an underscore. Thank you.

**Comment by JamesIves** [comment]
Please provide some logs, a repo I can clone so I can reproduce this issue, and the workflow you are using. It would also be helpful to provide some additional context too of the behavior you expect vs what you are getting.

**Comment by fbrier** [comment]
It took a bit of effort to reproduce the environment on Github, as this problem was occurring on private Github Enterprise servers with proprietary code. Wasted effort, as it WORKS on Github.com. The file in question is prefixed with "md" in front of the underscore. Apparently, this is another artifact of the company being behind at least one GHE version. I am closing this issue. My apologies.
