### ISSUE TITLE
operating system you're using is not supported warning

### ISSUE THREAD

**Issue by humble-barnacle001** [JamesIves/github-pages-deploy-action#995]
## Describe the bug

When using the action I get the warning
```
The operating system you're using is not supported and results may be varied. Please refer to the documentation for more details. ❗
```

## Reproduction Steps

Use the workflow with `ubuntu-latest` runner on github

## Logs

```
Checking configuration and starting deployment… 🚦
The operating system you're using is not supported and results may be varied. Please refer to the documentation for more details. ❗
Deploying using Deploy Token… 🔑
```

## Workflow

https://github.com/humble-barnacle001/fetch-covid-update-bot/actions/runs/1674239476/workflow

## Additional Comments

Workflow run: https://github.com/humble-barnacle001/fetch-covid-update-bot/runs/4753789761

**Comment by JamesIves** [comment]
This has been resolved in version 4.2.1, thanks for the report!
